[top]
components : coder@Transcoder 
out : connect2
out : inconnect2
out : query2
out : publish2
out : remove2
in : connect1
in : inconnect1
in : query1
in : publish1
in : remove1
Link : connect1 connect1@coder
Link : inconnect1 inconnect1@coder
Link : query1 query1@coder
Link : publish1 publish1@coder
Link : remove1 remove1@coder
Link : connect2@coder connect2
Link : inconnect2@coder inconnect2
Link : query2@coder query2
Link : publish2@coder publish2
Link : remove2@coder remove2
