[top]
components : Network IdGen@msgIdGen log@Logger Linker@LinkFinder Peer0 Peer1 Peer2 Peer3 Peer4 Peer5 Peer6 Peer7 Peer8 Peer9 Peer10 Peer11 Peer12 Peer13 Peer14 Peer15 Peer16 Peer17 Peer18 Peer19 Peer20 Peer21 Peer22 Peer23 Peer24 Peer25 Peer26 Peer27 Peer28 Peer29 Peer30 Peer31 Peer32 Peer33 Peer34 Peer35 Peer36 Peer37 Peer38 Peer39 Peer40 Peer41 Peer42 Peer43 Peer44 Peer45 Peer46 Peer47 Peer48 Peer49
Link : LinkFind@Peer0 in_q@Linker
Link : LinkFind@Peer1 in_q@Linker
Link : LinkFind@Peer2 in_q@Linker
Link : LinkFind@Peer3 in_q@Linker
Link : LinkFind@Peer4 in_q@Linker
Link : LinkFind@Peer5 in_q@Linker
Link : LinkFind@Peer6 in_q@Linker
Link : LinkFind@Peer7 in_q@Linker
Link : LinkFind@Peer8 in_q@Linker
Link : LinkFind@Peer9 in_q@Linker
Link : LinkFind@Peer10 in_q@Linker
Link : LinkFind@Peer11 in_q@Linker
Link : LinkFind@Peer12 in_q@Linker
Link : LinkFind@Peer13 in_q@Linker
Link : LinkFind@Peer14 in_q@Linker
Link : LinkFind@Peer15 in_q@Linker
Link : LinkFind@Peer16 in_q@Linker
Link : LinkFind@Peer17 in_q@Linker
Link : LinkFind@Peer18 in_q@Linker
Link : LinkFind@Peer19 in_q@Linker
Link : LinkFind@Peer20 in_q@Linker
Link : LinkFind@Peer21 in_q@Linker
Link : LinkFind@Peer22 in_q@Linker
Link : LinkFind@Peer23 in_q@Linker
Link : LinkFind@Peer24 in_q@Linker
Link : LinkFind@Peer25 in_q@Linker
Link : LinkFind@Peer26 in_q@Linker
Link : LinkFind@Peer27 in_q@Linker
Link : LinkFind@Peer28 in_q@Linker
Link : LinkFind@Peer29 in_q@Linker
Link : LinkFind@Peer30 in_q@Linker
Link : LinkFind@Peer31 in_q@Linker
Link : LinkFind@Peer32 in_q@Linker
Link : LinkFind@Peer33 in_q@Linker
Link : LinkFind@Peer34 in_q@Linker
Link : LinkFind@Peer35 in_q@Linker
Link : LinkFind@Peer36 in_q@Linker
Link : LinkFind@Peer37 in_q@Linker
Link : LinkFind@Peer38 in_q@Linker
Link : LinkFind@Peer39 in_q@Linker
Link : LinkFind@Peer40 in_q@Linker
Link : LinkFind@Peer41 in_q@Linker
Link : LinkFind@Peer42 in_q@Linker
Link : LinkFind@Peer43 in_q@Linker
Link : LinkFind@Peer44 in_q@Linker
Link : LinkFind@Peer45 in_q@Linker
Link : LinkFind@Peer46 in_q@Linker
Link : LinkFind@Peer47 in_q@Linker
Link : LinkFind@Peer48 in_q@Linker
Link : LinkFind@Peer49 in_q@Linker
Link : q_out0@Linker Link_in@Peer0
Link : q_out1@Linker Link_in@Peer1
Link : q_out2@Linker Link_in@Peer2
Link : q_out3@Linker Link_in@Peer3
Link : q_out4@Linker Link_in@Peer4
Link : q_out5@Linker Link_in@Peer5
Link : q_out6@Linker Link_in@Peer6
Link : q_out7@Linker Link_in@Peer7
Link : q_out8@Linker Link_in@Peer8
Link : q_out9@Linker Link_in@Peer9
Link : q_out10@Linker Link_in@Peer10
Link : q_out11@Linker Link_in@Peer11
Link : q_out12@Linker Link_in@Peer12
Link : q_out13@Linker Link_in@Peer13
Link : q_out14@Linker Link_in@Peer14
Link : q_out15@Linker Link_in@Peer15
Link : q_out16@Linker Link_in@Peer16
Link : q_out17@Linker Link_in@Peer17
Link : q_out18@Linker Link_in@Peer18
Link : q_out19@Linker Link_in@Peer19
Link : q_out20@Linker Link_in@Peer20
Link : q_out21@Linker Link_in@Peer21
Link : q_out22@Linker Link_in@Peer22
Link : q_out23@Linker Link_in@Peer23
Link : q_out24@Linker Link_in@Peer24
Link : q_out25@Linker Link_in@Peer25
Link : q_out26@Linker Link_in@Peer26
Link : q_out27@Linker Link_in@Peer27
Link : q_out28@Linker Link_in@Peer28
Link : q_out29@Linker Link_in@Peer29
Link : q_out30@Linker Link_in@Peer30
Link : q_out31@Linker Link_in@Peer31
Link : q_out32@Linker Link_in@Peer32
Link : q_out33@Linker Link_in@Peer33
Link : q_out34@Linker Link_in@Peer34
Link : q_out35@Linker Link_in@Peer35
Link : q_out36@Linker Link_in@Peer36
Link : q_out37@Linker Link_in@Peer37
Link : q_out38@Linker Link_in@Peer38
Link : q_out39@Linker Link_in@Peer39
Link : q_out40@Linker Link_in@Peer40
Link : q_out41@Linker Link_in@Peer41
Link : q_out42@Linker Link_in@Peer42
Link : q_out43@Linker Link_in@Peer43
Link : q_out44@Linker Link_in@Peer44
Link : q_out45@Linker Link_in@Peer45
Link : q_out46@Linker Link_in@Peer46
Link : q_out47@Linker Link_in@Peer47
Link : q_out48@Linker Link_in@Peer48
Link : q_out49@Linker Link_in@Peer49
Link : queryhit@Peer0 qhit_in@log
Link : queryhit@Peer1 qhit_in@log
Link : queryhit@Peer2 qhit_in@log
Link : queryhit@Peer3 qhit_in@log
Link : queryhit@Peer4 qhit_in@log
Link : queryhit@Peer5 qhit_in@log
Link : queryhit@Peer6 qhit_in@log
Link : queryhit@Peer7 qhit_in@log
Link : queryhit@Peer8 qhit_in@log
Link : queryhit@Peer9 qhit_in@log
Link : queryhit@Peer10 qhit_in@log
Link : queryhit@Peer11 qhit_in@log
Link : queryhit@Peer12 qhit_in@log
Link : queryhit@Peer13 qhit_in@log
Link : queryhit@Peer14 qhit_in@log
Link : queryhit@Peer15 qhit_in@log
Link : queryhit@Peer16 qhit_in@log
Link : queryhit@Peer17 qhit_in@log
Link : queryhit@Peer18 qhit_in@log
Link : queryhit@Peer19 qhit_in@log
Link : queryhit@Peer20 qhit_in@log
Link : queryhit@Peer21 qhit_in@log
Link : queryhit@Peer22 qhit_in@log
Link : queryhit@Peer23 qhit_in@log
Link : queryhit@Peer24 qhit_in@log
Link : queryhit@Peer25 qhit_in@log
Link : queryhit@Peer26 qhit_in@log
Link : queryhit@Peer27 qhit_in@log
Link : queryhit@Peer28 qhit_in@log
Link : queryhit@Peer29 qhit_in@log
Link : queryhit@Peer30 qhit_in@log
Link : queryhit@Peer31 qhit_in@log
Link : queryhit@Peer32 qhit_in@log
Link : queryhit@Peer33 qhit_in@log
Link : queryhit@Peer34 qhit_in@log
Link : queryhit@Peer35 qhit_in@log
Link : queryhit@Peer36 qhit_in@log
Link : queryhit@Peer37 qhit_in@log
Link : queryhit@Peer38 qhit_in@log
Link : queryhit@Peer39 qhit_in@log
Link : queryhit@Peer40 qhit_in@log
Link : queryhit@Peer41 qhit_in@log
Link : queryhit@Peer42 qhit_in@log
Link : queryhit@Peer43 qhit_in@log
Link : queryhit@Peer44 qhit_in@log
Link : queryhit@Peer45 qhit_in@log
Link : queryhit@Peer46 qhit_in@log
Link : queryhit@Peer47 qhit_in@log
Link : queryhit@Peer48 qhit_in@log
Link : queryhit@Peer49 qhit_in@log
Link : disconnect@Peer0 in_disconnect@log
Link : disconnect@Peer1 in_disconnect@log
Link : disconnect@Peer2 in_disconnect@log
Link : disconnect@Peer3 in_disconnect@log
Link : disconnect@Peer4 in_disconnect@log
Link : disconnect@Peer5 in_disconnect@log
Link : disconnect@Peer6 in_disconnect@log
Link : disconnect@Peer7 in_disconnect@log
Link : disconnect@Peer8 in_disconnect@log
Link : disconnect@Peer9 in_disconnect@log
Link : disconnect@Peer10 in_disconnect@log
Link : disconnect@Peer11 in_disconnect@log
Link : disconnect@Peer12 in_disconnect@log
Link : disconnect@Peer13 in_disconnect@log
Link : disconnect@Peer14 in_disconnect@log
Link : disconnect@Peer15 in_disconnect@log
Link : disconnect@Peer16 in_disconnect@log
Link : disconnect@Peer17 in_disconnect@log
Link : disconnect@Peer18 in_disconnect@log
Link : disconnect@Peer19 in_disconnect@log
Link : disconnect@Peer20 in_disconnect@log
Link : disconnect@Peer21 in_disconnect@log
Link : disconnect@Peer22 in_disconnect@log
Link : disconnect@Peer23 in_disconnect@log
Link : disconnect@Peer24 in_disconnect@log
Link : disconnect@Peer25 in_disconnect@log
Link : disconnect@Peer26 in_disconnect@log
Link : disconnect@Peer27 in_disconnect@log
Link : disconnect@Peer28 in_disconnect@log
Link : disconnect@Peer29 in_disconnect@log
Link : disconnect@Peer30 in_disconnect@log
Link : disconnect@Peer31 in_disconnect@log
Link : disconnect@Peer32 in_disconnect@log
Link : disconnect@Peer33 in_disconnect@log
Link : disconnect@Peer34 in_disconnect@log
Link : disconnect@Peer35 in_disconnect@log
Link : disconnect@Peer36 in_disconnect@log
Link : disconnect@Peer37 in_disconnect@log
Link : disconnect@Peer38 in_disconnect@log
Link : disconnect@Peer39 in_disconnect@log
Link : disconnect@Peer40 in_disconnect@log
Link : disconnect@Peer41 in_disconnect@log
Link : disconnect@Peer42 in_disconnect@log
Link : disconnect@Peer43 in_disconnect@log
Link : disconnect@Peer44 in_disconnect@log
Link : disconnect@Peer45 in_disconnect@log
Link : disconnect@Peer46 in_disconnect@log
Link : disconnect@Peer47 in_disconnect@log
Link : disconnect@Peer48 in_disconnect@log
Link : disconnect@Peer49 in_disconnect@log
Link : connect@Peer0 in_connect@log
Link : connect@Peer1 in_connect@log
Link : connect@Peer2 in_connect@log
Link : connect@Peer3 in_connect@log
Link : connect@Peer4 in_connect@log
Link : connect@Peer5 in_connect@log
Link : connect@Peer6 in_connect@log
Link : connect@Peer7 in_connect@log
Link : connect@Peer8 in_connect@log
Link : connect@Peer9 in_connect@log
Link : connect@Peer10 in_connect@log
Link : connect@Peer11 in_connect@log
Link : connect@Peer12 in_connect@log
Link : connect@Peer13 in_connect@log
Link : connect@Peer14 in_connect@log
Link : connect@Peer15 in_connect@log
Link : connect@Peer16 in_connect@log
Link : connect@Peer17 in_connect@log
Link : connect@Peer18 in_connect@log
Link : connect@Peer19 in_connect@log
Link : connect@Peer20 in_connect@log
Link : connect@Peer21 in_connect@log
Link : connect@Peer22 in_connect@log
Link : connect@Peer23 in_connect@log
Link : connect@Peer24 in_connect@log
Link : connect@Peer25 in_connect@log
Link : connect@Peer26 in_connect@log
Link : connect@Peer27 in_connect@log
Link : connect@Peer28 in_connect@log
Link : connect@Peer29 in_connect@log
Link : connect@Peer30 in_connect@log
Link : connect@Peer31 in_connect@log
Link : connect@Peer32 in_connect@log
Link : connect@Peer33 in_connect@log
Link : connect@Peer34 in_connect@log
Link : connect@Peer35 in_connect@log
Link : connect@Peer36 in_connect@log
Link : connect@Peer37 in_connect@log
Link : connect@Peer38 in_connect@log
Link : connect@Peer39 in_connect@log
Link : connect@Peer40 in_connect@log
Link : connect@Peer41 in_connect@log
Link : connect@Peer42 in_connect@log
Link : connect@Peer43 in_connect@log
Link : connect@Peer44 in_connect@log
Link : connect@Peer45 in_connect@log
Link : connect@Peer46 in_connect@log
Link : connect@Peer47 in_connect@log
Link : connect@Peer48 in_connect@log
Link : connect@Peer49 in_connect@log
Link : out_0@IdGen in_query@log
Link : out_1@IdGen in_query@log
Link : out_2@IdGen in_query@log
Link : out_3@IdGen in_query@log
Link : out_4@IdGen in_query@log
Link : out_5@IdGen in_query@log
Link : out_6@IdGen in_query@log
Link : out_7@IdGen in_query@log
Link : out_8@IdGen in_query@log
Link : out_9@IdGen in_query@log
Link : out_10@IdGen in_query@log
Link : out_11@IdGen in_query@log
Link : out_12@IdGen in_query@log
Link : out_13@IdGen in_query@log
Link : out_14@IdGen in_query@log
Link : out_15@IdGen in_query@log
Link : out_16@IdGen in_query@log
Link : out_17@IdGen in_query@log
Link : out_18@IdGen in_query@log
Link : out_19@IdGen in_query@log
Link : out_20@IdGen in_query@log
Link : out_21@IdGen in_query@log
Link : out_22@IdGen in_query@log
Link : out_23@IdGen in_query@log
Link : out_24@IdGen in_query@log
Link : out_25@IdGen in_query@log
Link : out_26@IdGen in_query@log
Link : out_27@IdGen in_query@log
Link : out_28@IdGen in_query@log
Link : out_29@IdGen in_query@log
Link : out_30@IdGen in_query@log
Link : out_31@IdGen in_query@log
Link : out_32@IdGen in_query@log
Link : out_33@IdGen in_query@log
Link : out_34@IdGen in_query@log
Link : out_35@IdGen in_query@log
Link : out_36@IdGen in_query@log
Link : out_37@IdGen in_query@log
Link : out_38@IdGen in_query@log
Link : out_39@IdGen in_query@log
Link : out_40@IdGen in_query@log
Link : out_41@IdGen in_query@log
Link : out_42@IdGen in_query@log
Link : out_43@IdGen in_query@log
Link : out_44@IdGen in_query@log
Link : out_45@IdGen in_query@log
Link : out_46@IdGen in_query@log
Link : out_47@IdGen in_query@log
Link : out_48@IdGen in_query@log
Link : out_49@IdGen in_query@log
Link : publish@Peer0 in_publish@log
Link : publish@Peer1 in_publish@log
Link : publish@Peer2 in_publish@log
Link : publish@Peer3 in_publish@log
Link : publish@Peer4 in_publish@log
Link : publish@Peer5 in_publish@log
Link : publish@Peer6 in_publish@log
Link : publish@Peer7 in_publish@log
Link : publish@Peer8 in_publish@log
Link : publish@Peer9 in_publish@log
Link : publish@Peer10 in_publish@log
Link : publish@Peer11 in_publish@log
Link : publish@Peer12 in_publish@log
Link : publish@Peer13 in_publish@log
Link : publish@Peer14 in_publish@log
Link : publish@Peer15 in_publish@log
Link : publish@Peer16 in_publish@log
Link : publish@Peer17 in_publish@log
Link : publish@Peer18 in_publish@log
Link : publish@Peer19 in_publish@log
Link : publish@Peer20 in_publish@log
Link : publish@Peer21 in_publish@log
Link : publish@Peer22 in_publish@log
Link : publish@Peer23 in_publish@log
Link : publish@Peer24 in_publish@log
Link : publish@Peer25 in_publish@log
Link : publish@Peer26 in_publish@log
Link : publish@Peer27 in_publish@log
Link : publish@Peer28 in_publish@log
Link : publish@Peer29 in_publish@log
Link : publish@Peer30 in_publish@log
Link : publish@Peer31 in_publish@log
Link : publish@Peer32 in_publish@log
Link : publish@Peer33 in_publish@log
Link : publish@Peer34 in_publish@log
Link : publish@Peer35 in_publish@log
Link : publish@Peer36 in_publish@log
Link : publish@Peer37 in_publish@log
Link : publish@Peer38 in_publish@log
Link : publish@Peer39 in_publish@log
Link : publish@Peer40 in_publish@log
Link : publish@Peer41 in_publish@log
Link : publish@Peer42 in_publish@log
Link : publish@Peer43 in_publish@log
Link : publish@Peer44 in_publish@log
Link : publish@Peer45 in_publish@log
Link : publish@Peer46 in_publish@log
Link : publish@Peer47 in_publish@log
Link : publish@Peer48 in_publish@log
Link : publish@Peer49 in_publish@log
Link : online@Peer0 in_online@Network
Link : online@Peer1 in_online@Network
Link : online@Peer2 in_online@Network
Link : online@Peer3 in_online@Network
Link : online@Peer4 in_online@Network
Link : online@Peer5 in_online@Network
Link : online@Peer6 in_online@Network
Link : online@Peer7 in_online@Network
Link : online@Peer8 in_online@Network
Link : online@Peer9 in_online@Network
Link : online@Peer10 in_online@Network
Link : online@Peer11 in_online@Network
Link : online@Peer12 in_online@Network
Link : online@Peer13 in_online@Network
Link : online@Peer14 in_online@Network
Link : online@Peer15 in_online@Network
Link : online@Peer16 in_online@Network
Link : online@Peer17 in_online@Network
Link : online@Peer18 in_online@Network
Link : online@Peer19 in_online@Network
Link : online@Peer20 in_online@Network
Link : online@Peer21 in_online@Network
Link : online@Peer22 in_online@Network
Link : online@Peer23 in_online@Network
Link : online@Peer24 in_online@Network
Link : online@Peer25 in_online@Network
Link : online@Peer26 in_online@Network
Link : online@Peer27 in_online@Network
Link : online@Peer28 in_online@Network
Link : online@Peer29 in_online@Network
Link : online@Peer30 in_online@Network
Link : online@Peer31 in_online@Network
Link : online@Peer32 in_online@Network
Link : online@Peer33 in_online@Network
Link : online@Peer34 in_online@Network
Link : online@Peer35 in_online@Network
Link : online@Peer36 in_online@Network
Link : online@Peer37 in_online@Network
Link : online@Peer38 in_online@Network
Link : online@Peer39 in_online@Network
Link : online@Peer40 in_online@Network
Link : online@Peer41 in_online@Network
Link : online@Peer42 in_online@Network
Link : online@Peer43 in_online@Network
Link : online@Peer44 in_online@Network
Link : online@Peer45 in_online@Network
Link : online@Peer46 in_online@Network
Link : online@Peer47 in_online@Network
Link : online@Peer48 in_online@Network
Link : online@Peer49 in_online@Network
Link : online@Peer0 in_online@log
Link : online@Peer1 in_online@log
Link : online@Peer2 in_online@log
Link : online@Peer3 in_online@log
Link : online@Peer4 in_online@log
Link : online@Peer5 in_online@log
Link : online@Peer6 in_online@log
Link : online@Peer7 in_online@log
Link : online@Peer8 in_online@log
Link : online@Peer9 in_online@log
Link : online@Peer10 in_online@log
Link : online@Peer11 in_online@log
Link : online@Peer12 in_online@log
Link : online@Peer13 in_online@log
Link : online@Peer14 in_online@log
Link : online@Peer15 in_online@log
Link : online@Peer16 in_online@log
Link : online@Peer17 in_online@log
Link : online@Peer18 in_online@log
Link : online@Peer19 in_online@log
Link : online@Peer20 in_online@log
Link : online@Peer21 in_online@log
Link : online@Peer22 in_online@log
Link : online@Peer23 in_online@log
Link : online@Peer24 in_online@log
Link : online@Peer25 in_online@log
Link : online@Peer26 in_online@log
Link : online@Peer27 in_online@log
Link : online@Peer28 in_online@log
Link : online@Peer29 in_online@log
Link : online@Peer30 in_online@log
Link : online@Peer31 in_online@log
Link : online@Peer32 in_online@log
Link : online@Peer33 in_online@log
Link : online@Peer34 in_online@log
Link : online@Peer35 in_online@log
Link : online@Peer36 in_online@log
Link : online@Peer37 in_online@log
Link : online@Peer38 in_online@log
Link : online@Peer39 in_online@log
Link : online@Peer40 in_online@log
Link : online@Peer41 in_online@log
Link : online@Peer42 in_online@log
Link : online@Peer43 in_online@log
Link : online@Peer44 in_online@log
Link : online@Peer45 in_online@log
Link : online@Peer46 in_online@log
Link : online@Peer47 in_online@log
Link : online@Peer48 in_online@log
Link : online@Peer49 in_online@log
Link : offline@Peer0 in_offline@log
Link : offline@Peer1 in_offline@log
Link : offline@Peer2 in_offline@log
Link : offline@Peer3 in_offline@log
Link : offline@Peer4 in_offline@log
Link : offline@Peer5 in_offline@log
Link : offline@Peer6 in_offline@log
Link : offline@Peer7 in_offline@log
Link : offline@Peer8 in_offline@log
Link : offline@Peer9 in_offline@log
Link : offline@Peer10 in_offline@log
Link : offline@Peer11 in_offline@log
Link : offline@Peer12 in_offline@log
Link : offline@Peer13 in_offline@log
Link : offline@Peer14 in_offline@log
Link : offline@Peer15 in_offline@log
Link : offline@Peer16 in_offline@log
Link : offline@Peer17 in_offline@log
Link : offline@Peer18 in_offline@log
Link : offline@Peer19 in_offline@log
Link : offline@Peer20 in_offline@log
Link : offline@Peer21 in_offline@log
Link : offline@Peer22 in_offline@log
Link : offline@Peer23 in_offline@log
Link : offline@Peer24 in_offline@log
Link : offline@Peer25 in_offline@log
Link : offline@Peer26 in_offline@log
Link : offline@Peer27 in_offline@log
Link : offline@Peer28 in_offline@log
Link : offline@Peer29 in_offline@log
Link : offline@Peer30 in_offline@log
Link : offline@Peer31 in_offline@log
Link : offline@Peer32 in_offline@log
Link : offline@Peer33 in_offline@log
Link : offline@Peer34 in_offline@log
Link : offline@Peer35 in_offline@log
Link : offline@Peer36 in_offline@log
Link : offline@Peer37 in_offline@log
Link : offline@Peer38 in_offline@log
Link : offline@Peer39 in_offline@log
Link : offline@Peer40 in_offline@log
Link : offline@Peer41 in_offline@log
Link : offline@Peer42 in_offline@log
Link : offline@Peer43 in_offline@log
Link : offline@Peer44 in_offline@log
Link : offline@Peer45 in_offline@log
Link : offline@Peer46 in_offline@log
Link : offline@Peer47 in_offline@log
Link : offline@Peer48 in_offline@log
Link : offline@Peer49 in_offline@log
Link : offline@Peer0 in_offline@Network
Link : offline@Peer1 in_offline@Network
Link : offline@Peer2 in_offline@Network
Link : offline@Peer3 in_offline@Network
Link : offline@Peer4 in_offline@Network
Link : offline@Peer5 in_offline@Network
Link : offline@Peer6 in_offline@Network
Link : offline@Peer7 in_offline@Network
Link : offline@Peer8 in_offline@Network
Link : offline@Peer9 in_offline@Network
Link : offline@Peer10 in_offline@Network
Link : offline@Peer11 in_offline@Network
Link : offline@Peer12 in_offline@Network
Link : offline@Peer13 in_offline@Network
Link : offline@Peer14 in_offline@Network
Link : offline@Peer15 in_offline@Network
Link : offline@Peer16 in_offline@Network
Link : offline@Peer17 in_offline@Network
Link : offline@Peer18 in_offline@Network
Link : offline@Peer19 in_offline@Network
Link : offline@Peer20 in_offline@Network
Link : offline@Peer21 in_offline@Network
Link : offline@Peer22 in_offline@Network
Link : offline@Peer23 in_offline@Network
Link : offline@Peer24 in_offline@Network
Link : offline@Peer25 in_offline@Network
Link : offline@Peer26 in_offline@Network
Link : offline@Peer27 in_offline@Network
Link : offline@Peer28 in_offline@Network
Link : offline@Peer29 in_offline@Network
Link : offline@Peer30 in_offline@Network
Link : offline@Peer31 in_offline@Network
Link : offline@Peer32 in_offline@Network
Link : offline@Peer33 in_offline@Network
Link : offline@Peer34 in_offline@Network
Link : offline@Peer35 in_offline@Network
Link : offline@Peer36 in_offline@Network
Link : offline@Peer37 in_offline@Network
Link : offline@Peer38 in_offline@Network
Link : offline@Peer39 in_offline@Network
Link : offline@Peer40 in_offline@Network
Link : offline@Peer41 in_offline@Network
Link : offline@Peer42 in_offline@Network
Link : offline@Peer43 in_offline@Network
Link : offline@Peer44 in_offline@Network
Link : offline@Peer45 in_offline@Network
Link : offline@Peer46 in_offline@Network
Link : offline@Peer47 in_offline@Network
Link : offline@Peer48 in_offline@Network
Link : offline@Peer49 in_offline@Network
Link : connect_out@Peer0 peer_connect@Network
Link : connect_out@Peer1 peer_connect@Network
Link : connect_out@Peer2 peer_connect@Network
Link : connect_out@Peer3 peer_connect@Network
Link : connect_out@Peer4 peer_connect@Network
Link : connect_out@Peer5 peer_connect@Network
Link : connect_out@Peer6 peer_connect@Network
Link : connect_out@Peer7 peer_connect@Network
Link : connect_out@Peer8 peer_connect@Network
Link : connect_out@Peer9 peer_connect@Network
Link : connect_out@Peer10 peer_connect@Network
Link : connect_out@Peer11 peer_connect@Network
Link : connect_out@Peer12 peer_connect@Network
Link : connect_out@Peer13 peer_connect@Network
Link : connect_out@Peer14 peer_connect@Network
Link : connect_out@Peer15 peer_connect@Network
Link : connect_out@Peer16 peer_connect@Network
Link : connect_out@Peer17 peer_connect@Network
Link : connect_out@Peer18 peer_connect@Network
Link : connect_out@Peer19 peer_connect@Network
Link : connect_out@Peer20 peer_connect@Network
Link : connect_out@Peer21 peer_connect@Network
Link : connect_out@Peer22 peer_connect@Network
Link : connect_out@Peer23 peer_connect@Network
Link : connect_out@Peer24 peer_connect@Network
Link : connect_out@Peer25 peer_connect@Network
Link : connect_out@Peer26 peer_connect@Network
Link : connect_out@Peer27 peer_connect@Network
Link : connect_out@Peer28 peer_connect@Network
Link : connect_out@Peer29 peer_connect@Network
Link : connect_out@Peer30 peer_connect@Network
Link : connect_out@Peer31 peer_connect@Network
Link : connect_out@Peer32 peer_connect@Network
Link : connect_out@Peer33 peer_connect@Network
Link : connect_out@Peer34 peer_connect@Network
Link : connect_out@Peer35 peer_connect@Network
Link : connect_out@Peer36 peer_connect@Network
Link : connect_out@Peer37 peer_connect@Network
Link : connect_out@Peer38 peer_connect@Network
Link : connect_out@Peer39 peer_connect@Network
Link : connect_out@Peer40 peer_connect@Network
Link : connect_out@Peer41 peer_connect@Network
Link : connect_out@Peer42 peer_connect@Network
Link : connect_out@Peer43 peer_connect@Network
Link : connect_out@Peer44 peer_connect@Network
Link : connect_out@Peer45 peer_connect@Network
Link : connect_out@Peer46 peer_connect@Network
Link : connect_out@Peer47 peer_connect@Network
Link : connect_out@Peer48 peer_connect@Network
Link : connect_out@Peer49 peer_connect@Network
Link : disconnect_out@Peer0 peer_disconnect@Network
Link : disconnect_out@Peer1 peer_disconnect@Network
Link : disconnect_out@Peer2 peer_disconnect@Network
Link : disconnect_out@Peer3 peer_disconnect@Network
Link : disconnect_out@Peer4 peer_disconnect@Network
Link : disconnect_out@Peer5 peer_disconnect@Network
Link : disconnect_out@Peer6 peer_disconnect@Network
Link : disconnect_out@Peer7 peer_disconnect@Network
Link : disconnect_out@Peer8 peer_disconnect@Network
Link : disconnect_out@Peer9 peer_disconnect@Network
Link : disconnect_out@Peer10 peer_disconnect@Network
Link : disconnect_out@Peer11 peer_disconnect@Network
Link : disconnect_out@Peer12 peer_disconnect@Network
Link : disconnect_out@Peer13 peer_disconnect@Network
Link : disconnect_out@Peer14 peer_disconnect@Network
Link : disconnect_out@Peer15 peer_disconnect@Network
Link : disconnect_out@Peer16 peer_disconnect@Network
Link : disconnect_out@Peer17 peer_disconnect@Network
Link : disconnect_out@Peer18 peer_disconnect@Network
Link : disconnect_out@Peer19 peer_disconnect@Network
Link : disconnect_out@Peer20 peer_disconnect@Network
Link : disconnect_out@Peer21 peer_disconnect@Network
Link : disconnect_out@Peer22 peer_disconnect@Network
Link : disconnect_out@Peer23 peer_disconnect@Network
Link : disconnect_out@Peer24 peer_disconnect@Network
Link : disconnect_out@Peer25 peer_disconnect@Network
Link : disconnect_out@Peer26 peer_disconnect@Network
Link : disconnect_out@Peer27 peer_disconnect@Network
Link : disconnect_out@Peer28 peer_disconnect@Network
Link : disconnect_out@Peer29 peer_disconnect@Network
Link : disconnect_out@Peer30 peer_disconnect@Network
Link : disconnect_out@Peer31 peer_disconnect@Network
Link : disconnect_out@Peer32 peer_disconnect@Network
Link : disconnect_out@Peer33 peer_disconnect@Network
Link : disconnect_out@Peer34 peer_disconnect@Network
Link : disconnect_out@Peer35 peer_disconnect@Network
Link : disconnect_out@Peer36 peer_disconnect@Network
Link : disconnect_out@Peer37 peer_disconnect@Network
Link : disconnect_out@Peer38 peer_disconnect@Network
Link : disconnect_out@Peer39 peer_disconnect@Network
Link : disconnect_out@Peer40 peer_disconnect@Network
Link : disconnect_out@Peer41 peer_disconnect@Network
Link : disconnect_out@Peer42 peer_disconnect@Network
Link : disconnect_out@Peer43 peer_disconnect@Network
Link : disconnect_out@Peer44 peer_disconnect@Network
Link : disconnect_out@Peer45 peer_disconnect@Network
Link : disconnect_out@Peer46 peer_disconnect@Network
Link : disconnect_out@Peer47 peer_disconnect@Network
Link : disconnect_out@Peer48 peer_disconnect@Network
Link : disconnect_out@Peer49 peer_disconnect@Network
Link : c_out0@Network connect_in@Peer0
Link : c_out1@Network connect_in@Peer1
Link : c_out2@Network connect_in@Peer2
Link : c_out3@Network connect_in@Peer3
Link : c_out4@Network connect_in@Peer4
Link : c_out5@Network connect_in@Peer5
Link : c_out6@Network connect_in@Peer6
Link : c_out7@Network connect_in@Peer7
Link : c_out8@Network connect_in@Peer8
Link : c_out9@Network connect_in@Peer9
Link : c_out10@Network connect_in@Peer10
Link : c_out11@Network connect_in@Peer11
Link : c_out12@Network connect_in@Peer12
Link : c_out13@Network connect_in@Peer13
Link : c_out14@Network connect_in@Peer14
Link : c_out15@Network connect_in@Peer15
Link : c_out16@Network connect_in@Peer16
Link : c_out17@Network connect_in@Peer17
Link : c_out18@Network connect_in@Peer18
Link : c_out19@Network connect_in@Peer19
Link : c_out20@Network connect_in@Peer20
Link : c_out21@Network connect_in@Peer21
Link : c_out22@Network connect_in@Peer22
Link : c_out23@Network connect_in@Peer23
Link : c_out24@Network connect_in@Peer24
Link : c_out25@Network connect_in@Peer25
Link : c_out26@Network connect_in@Peer26
Link : c_out27@Network connect_in@Peer27
Link : c_out28@Network connect_in@Peer28
Link : c_out29@Network connect_in@Peer29
Link : c_out30@Network connect_in@Peer30
Link : c_out31@Network connect_in@Peer31
Link : c_out32@Network connect_in@Peer32
Link : c_out33@Network connect_in@Peer33
Link : c_out34@Network connect_in@Peer34
Link : c_out35@Network connect_in@Peer35
Link : c_out36@Network connect_in@Peer36
Link : c_out37@Network connect_in@Peer37
Link : c_out38@Network connect_in@Peer38
Link : c_out39@Network connect_in@Peer39
Link : c_out40@Network connect_in@Peer40
Link : c_out41@Network connect_in@Peer41
Link : c_out42@Network connect_in@Peer42
Link : c_out43@Network connect_in@Peer43
Link : c_out44@Network connect_in@Peer44
Link : c_out45@Network connect_in@Peer45
Link : c_out46@Network connect_in@Peer46
Link : c_out47@Network connect_in@Peer47
Link : c_out48@Network connect_in@Peer48
Link : c_out49@Network connect_in@Peer49
Link : query_out@Peer0 msg_in@IdGen
Link : query_out@Peer1 msg_in@IdGen
Link : query_out@Peer2 msg_in@IdGen
Link : query_out@Peer3 msg_in@IdGen
Link : query_out@Peer4 msg_in@IdGen
Link : query_out@Peer5 msg_in@IdGen
Link : query_out@Peer6 msg_in@IdGen
Link : query_out@Peer7 msg_in@IdGen
Link : query_out@Peer8 msg_in@IdGen
Link : query_out@Peer9 msg_in@IdGen
Link : query_out@Peer10 msg_in@IdGen
Link : query_out@Peer11 msg_in@IdGen
Link : query_out@Peer12 msg_in@IdGen
Link : query_out@Peer13 msg_in@IdGen
Link : query_out@Peer14 msg_in@IdGen
Link : query_out@Peer15 msg_in@IdGen
Link : query_out@Peer16 msg_in@IdGen
Link : query_out@Peer17 msg_in@IdGen
Link : query_out@Peer18 msg_in@IdGen
Link : query_out@Peer19 msg_in@IdGen
Link : query_out@Peer20 msg_in@IdGen
Link : query_out@Peer21 msg_in@IdGen
Link : query_out@Peer22 msg_in@IdGen
Link : query_out@Peer23 msg_in@IdGen
Link : query_out@Peer24 msg_in@IdGen
Link : query_out@Peer25 msg_in@IdGen
Link : query_out@Peer26 msg_in@IdGen
Link : query_out@Peer27 msg_in@IdGen
Link : query_out@Peer28 msg_in@IdGen
Link : query_out@Peer29 msg_in@IdGen
Link : query_out@Peer30 msg_in@IdGen
Link : query_out@Peer31 msg_in@IdGen
Link : query_out@Peer32 msg_in@IdGen
Link : query_out@Peer33 msg_in@IdGen
Link : query_out@Peer34 msg_in@IdGen
Link : query_out@Peer35 msg_in@IdGen
Link : query_out@Peer36 msg_in@IdGen
Link : query_out@Peer37 msg_in@IdGen
Link : query_out@Peer38 msg_in@IdGen
Link : query_out@Peer39 msg_in@IdGen
Link : query_out@Peer40 msg_in@IdGen
Link : query_out@Peer41 msg_in@IdGen
Link : query_out@Peer42 msg_in@IdGen
Link : query_out@Peer43 msg_in@IdGen
Link : query_out@Peer44 msg_in@IdGen
Link : query_out@Peer45 msg_in@IdGen
Link : query_out@Peer46 msg_in@IdGen
Link : query_out@Peer47 msg_in@IdGen
Link : query_out@Peer48 msg_in@IdGen
Link : query_out@Peer49 msg_in@IdGen
Link : out_0@IdGen query_in@Peer0
Link : out_1@IdGen query_in@Peer1
Link : out_2@IdGen query_in@Peer2
Link : out_3@IdGen query_in@Peer3
Link : out_4@IdGen query_in@Peer4
Link : out_5@IdGen query_in@Peer5
Link : out_6@IdGen query_in@Peer6
Link : out_7@IdGen query_in@Peer7
Link : out_8@IdGen query_in@Peer8
Link : out_9@IdGen query_in@Peer9
Link : out_10@IdGen query_in@Peer10
Link : out_11@IdGen query_in@Peer11
Link : out_12@IdGen query_in@Peer12
Link : out_13@IdGen query_in@Peer13
Link : out_14@IdGen query_in@Peer14
Link : out_15@IdGen query_in@Peer15
Link : out_16@IdGen query_in@Peer16
Link : out_17@IdGen query_in@Peer17
Link : out_18@IdGen query_in@Peer18
Link : out_19@IdGen query_in@Peer19
Link : out_20@IdGen query_in@Peer20
Link : out_21@IdGen query_in@Peer21
Link : out_22@IdGen query_in@Peer22
Link : out_23@IdGen query_in@Peer23
Link : out_24@IdGen query_in@Peer24
Link : out_25@IdGen query_in@Peer25
Link : out_26@IdGen query_in@Peer26
Link : out_27@IdGen query_in@Peer27
Link : out_28@IdGen query_in@Peer28
Link : out_29@IdGen query_in@Peer29
Link : out_30@IdGen query_in@Peer30
Link : out_31@IdGen query_in@Peer31
Link : out_32@IdGen query_in@Peer32
Link : out_33@IdGen query_in@Peer33
Link : out_34@IdGen query_in@Peer34
Link : out_35@IdGen query_in@Peer35
Link : out_36@IdGen query_in@Peer36
Link : out_37@IdGen query_in@Peer37
Link : out_38@IdGen query_in@Peer38
Link : out_39@IdGen query_in@Peer39
Link : out_40@IdGen query_in@Peer40
Link : out_41@IdGen query_in@Peer41
Link : out_42@IdGen query_in@Peer42
Link : out_43@IdGen query_in@Peer43
Link : out_44@IdGen query_in@Peer44
Link : out_45@IdGen query_in@Peer45
Link : out_46@IdGen query_in@Peer46
Link : out_47@IdGen query_in@Peer47
Link : out_48@IdGen query_in@Peer48
Link : out_49@IdGen query_in@Peer49
Link : q_out@Peer0 inroute@Network
Link : q_out@Peer1 inroute@Network
Link : q_out@Peer2 inroute@Network
Link : q_out@Peer3 inroute@Network
Link : q_out@Peer4 inroute@Network
Link : q_out@Peer5 inroute@Network
Link : q_out@Peer6 inroute@Network
Link : q_out@Peer7 inroute@Network
Link : q_out@Peer8 inroute@Network
Link : q_out@Peer9 inroute@Network
Link : q_out@Peer10 inroute@Network
Link : q_out@Peer11 inroute@Network
Link : q_out@Peer12 inroute@Network
Link : q_out@Peer13 inroute@Network
Link : q_out@Peer14 inroute@Network
Link : q_out@Peer15 inroute@Network
Link : q_out@Peer16 inroute@Network
Link : q_out@Peer17 inroute@Network
Link : q_out@Peer18 inroute@Network
Link : q_out@Peer19 inroute@Network
Link : q_out@Peer20 inroute@Network
Link : q_out@Peer21 inroute@Network
Link : q_out@Peer22 inroute@Network
Link : q_out@Peer23 inroute@Network
Link : q_out@Peer24 inroute@Network
Link : q_out@Peer25 inroute@Network
Link : q_out@Peer26 inroute@Network
Link : q_out@Peer27 inroute@Network
Link : q_out@Peer28 inroute@Network
Link : q_out@Peer29 inroute@Network
Link : q_out@Peer30 inroute@Network
Link : q_out@Peer31 inroute@Network
Link : q_out@Peer32 inroute@Network
Link : q_out@Peer33 inroute@Network
Link : q_out@Peer34 inroute@Network
Link : q_out@Peer35 inroute@Network
Link : q_out@Peer36 inroute@Network
Link : q_out@Peer37 inroute@Network
Link : q_out@Peer38 inroute@Network
Link : q_out@Peer39 inroute@Network
Link : q_out@Peer40 inroute@Network
Link : q_out@Peer41 inroute@Network
Link : q_out@Peer42 inroute@Network
Link : q_out@Peer43 inroute@Network
Link : q_out@Peer44 inroute@Network
Link : q_out@Peer45 inroute@Network
Link : q_out@Peer46 inroute@Network
Link : q_out@Peer47 inroute@Network
Link : q_out@Peer48 inroute@Network
Link : q_out@Peer49 inroute@Network
Link : route_out0@Network q_in@Peer0
Link : route_out1@Network q_in@Peer1
Link : route_out2@Network q_in@Peer2
Link : route_out3@Network q_in@Peer3
Link : route_out4@Network q_in@Peer4
Link : route_out5@Network q_in@Peer5
Link : route_out6@Network q_in@Peer6
Link : route_out7@Network q_in@Peer7
Link : route_out8@Network q_in@Peer8
Link : route_out9@Network q_in@Peer9
Link : route_out10@Network q_in@Peer10
Link : route_out11@Network q_in@Peer11
Link : route_out12@Network q_in@Peer12
Link : route_out13@Network q_in@Peer13
Link : route_out14@Network q_in@Peer14
Link : route_out15@Network q_in@Peer15
Link : route_out16@Network q_in@Peer16
Link : route_out17@Network q_in@Peer17
Link : route_out18@Network q_in@Peer18
Link : route_out19@Network q_in@Peer19
Link : route_out20@Network q_in@Peer20
Link : route_out21@Network q_in@Peer21
Link : route_out22@Network q_in@Peer22
Link : route_out23@Network q_in@Peer23
Link : route_out24@Network q_in@Peer24
Link : route_out25@Network q_in@Peer25
Link : route_out26@Network q_in@Peer26
Link : route_out27@Network q_in@Peer27
Link : route_out28@Network q_in@Peer28
Link : route_out29@Network q_in@Peer29
Link : route_out30@Network q_in@Peer30
Link : route_out31@Network q_in@Peer31
Link : route_out32@Network q_in@Peer32
Link : route_out33@Network q_in@Peer33
Link : route_out34@Network q_in@Peer34
Link : route_out35@Network q_in@Peer35
Link : route_out36@Network q_in@Peer36
Link : route_out37@Network q_in@Peer37
Link : route_out38@Network q_in@Peer38
Link : route_out39@Network q_in@Peer39
Link : route_out40@Network q_in@Peer40
Link : route_out41@Network q_in@Peer41
Link : route_out42@Network q_in@Peer42
Link : route_out43@Network q_in@Peer43
Link : route_out44@Network q_in@Peer44
Link : route_out45@Network q_in@Peer45
Link : route_out46@Network q_in@Peer46
Link : route_out47@Network q_in@Peer47
Link : route_out48@Network q_in@Peer48
Link : route_out49@Network q_in@Peer49
Link : queryreachespeer@Peer0 queryReached@log
Link : queryreachespeer@Peer1 queryReached@log
Link : queryreachespeer@Peer2 queryReached@log
Link : queryreachespeer@Peer3 queryReached@log
Link : queryreachespeer@Peer4 queryReached@log
Link : queryreachespeer@Peer5 queryReached@log
Link : queryreachespeer@Peer6 queryReached@log
Link : queryreachespeer@Peer7 queryReached@log
Link : queryreachespeer@Peer8 queryReached@log
Link : queryreachespeer@Peer9 queryReached@log
Link : queryreachespeer@Peer10 queryReached@log
Link : queryreachespeer@Peer11 queryReached@log
Link : queryreachespeer@Peer12 queryReached@log
Link : queryreachespeer@Peer13 queryReached@log
Link : queryreachespeer@Peer14 queryReached@log
Link : queryreachespeer@Peer15 queryReached@log
Link : queryreachespeer@Peer16 queryReached@log
Link : queryreachespeer@Peer17 queryReached@log
Link : queryreachespeer@Peer18 queryReached@log
Link : queryreachespeer@Peer19 queryReached@log
Link : queryreachespeer@Peer20 queryReached@log
Link : queryreachespeer@Peer21 queryReached@log
Link : queryreachespeer@Peer22 queryReached@log
Link : queryreachespeer@Peer23 queryReached@log
Link : queryreachespeer@Peer24 queryReached@log
Link : queryreachespeer@Peer25 queryReached@log
Link : queryreachespeer@Peer26 queryReached@log
Link : queryreachespeer@Peer27 queryReached@log
Link : queryreachespeer@Peer28 queryReached@log
Link : queryreachespeer@Peer29 queryReached@log
Link : queryreachespeer@Peer30 queryReached@log
Link : queryreachespeer@Peer31 queryReached@log
Link : queryreachespeer@Peer32 queryReached@log
Link : queryreachespeer@Peer33 queryReached@log
Link : queryreachespeer@Peer34 queryReached@log
Link : queryreachespeer@Peer35 queryReached@log
Link : queryreachespeer@Peer36 queryReached@log
Link : queryreachespeer@Peer37 queryReached@log
Link : queryreachespeer@Peer38 queryReached@log
Link : queryreachespeer@Peer39 queryReached@log
Link : queryreachespeer@Peer40 queryReached@log
Link : queryreachespeer@Peer41 queryReached@log
Link : queryreachespeer@Peer42 queryReached@log
Link : queryreachespeer@Peer43 queryReached@log
Link : queryreachespeer@Peer44 queryReached@log
Link : queryreachespeer@Peer45 queryReached@log
Link : queryreachespeer@Peer46 queryReached@log
Link : queryreachespeer@Peer47 queryReached@log
Link : queryreachespeer@Peer48 queryReached@log
Link : queryreachespeer@Peer49 queryReached@log
[Linker]
datafile : serverdoc.dat

[Peer0]
components : session0@RandomSurfer connector0@ConnectionManager gnut0@Router server0@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session0 in_online@connector0
Link : online@session0 online
Link : offline@session0 in_offline@connector0
Link : out_offline@connector0 offline
Link : query@session0 query_out
Link : query@session0 publish@server0
Link : publish@session0 publish@server0
Link : p_out@server0 publish
Link : link@server0 LinkFind
Link : remove@session0 remove@server0
Link : out_connect@connector0 connect_out
Link : out_disconnect@connector0 disconnect_out
Link : connect_in in_connect@connector0
Link : connect_in connections@gnut0
Link : q_in q_in@gnut0
Link : q_out@gnut0 q_out
Link : localOut@gnut0 peer_in@server0
Link : Link_in peer_in@server0
Link : localOut@gnut0 queryreachespeer
Link : queryhit@server0 q_in@gnut0
Link : queryhit@server0 queryhit
Link : query_in query@gnut0
Link : connect_out@gnut0 connect
Link : disconnect_out@gnut0 disconnect
Link : qhit_out@gnut0 queryhit@session0

[session0]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 14,51,85,95,134,197,234,235,242,264,351,353,383,398,402,442,445,573,597,602,608,614,632,693,719,719,726,839,854,862,873,880,893,945,947
whoAmI : 0
TimeToLive : 4

[connector0]
friendlist : 1,2,3,32
whoAmI : 0 

[server0]
capacity : 60


[Peer1]
components : session1@RandomSurfer connector1@ConnectionManager gnut1@Router server1@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session1 in_online@connector1
Link : online@session1 online
Link : offline@session1 in_offline@connector1
Link : out_offline@connector1 offline
Link : query@session1 query_out
Link : query@session1 publish@server1
Link : publish@session1 publish@server1
Link : p_out@server1 publish
Link : link@server1 LinkFind
Link : remove@session1 remove@server1
Link : out_connect@connector1 connect_out
Link : out_disconnect@connector1 disconnect_out
Link : connect_in in_connect@connector1
Link : connect_in connections@gnut1
Link : q_in q_in@gnut1
Link : q_out@gnut1 q_out
Link : localOut@gnut1 peer_in@server1
Link : Link_in peer_in@server1
Link : localOut@gnut1 queryreachespeer
Link : queryhit@server1 q_in@gnut1
Link : queryhit@server1 queryhit
Link : query_in query@gnut1
Link : connect_out@gnut1 connect
Link : disconnect_out@gnut1 disconnect
Link : qhit_out@gnut1 queryhit@session1

[session1]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 30,42,84,94,120,154,166,168,208,243,243,261,303,345,367,376,382,399,411,412,425,505,540,542,545,596,598,615,627,758,788,874,878,902,954
whoAmI : 1
TimeToLive : 4

[connector1]
friendlist : 0,2,3,4,6,9,13,16,49
whoAmI : 1 

[server1]
capacity : 60


[Peer2]
components : session2@RandomSurfer connector2@ConnectionManager gnut2@Router server2@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session2 in_online@connector2
Link : online@session2 online
Link : offline@session2 in_offline@connector2
Link : out_offline@connector2 offline
Link : query@session2 query_out
Link : query@session2 publish@server2
Link : publish@session2 publish@server2
Link : p_out@server2 publish
Link : link@server2 LinkFind
Link : remove@session2 remove@server2
Link : out_connect@connector2 connect_out
Link : out_disconnect@connector2 disconnect_out
Link : connect_in in_connect@connector2
Link : connect_in connections@gnut2
Link : q_in q_in@gnut2
Link : q_out@gnut2 q_out
Link : localOut@gnut2 peer_in@server2
Link : Link_in peer_in@server2
Link : localOut@gnut2 queryreachespeer
Link : queryhit@server2 q_in@gnut2
Link : queryhit@server2 queryhit
Link : query_in query@gnut2
Link : connect_out@gnut2 connect
Link : disconnect_out@gnut2 disconnect
Link : qhit_out@gnut2 queryhit@session2

[session2]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 21,45,83,124,132,155,220,240,244,265,278,292,323,329,337,342,373,398,399,435,467,628,634,638,638,644,666,680,682,688,726,765,793,803,810,822,866,867,904,947,954
whoAmI : 2
TimeToLive : 4

[connector2]
friendlist : 1,0,4,6
whoAmI : 2 

[server2]
capacity : 60


[Peer3]
components : session3@RandomSurfer connector3@ConnectionManager gnut3@Router server3@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session3 in_online@connector3
Link : online@session3 online
Link : offline@session3 in_offline@connector3
Link : out_offline@connector3 offline
Link : query@session3 query_out
Link : query@session3 publish@server3
Link : publish@session3 publish@server3
Link : p_out@server3 publish
Link : link@server3 LinkFind
Link : remove@session3 remove@server3
Link : out_connect@connector3 connect_out
Link : out_disconnect@connector3 disconnect_out
Link : connect_in in_connect@connector3
Link : connect_in connections@gnut3
Link : q_in q_in@gnut3
Link : q_out@gnut3 q_out
Link : localOut@gnut3 peer_in@server3
Link : Link_in peer_in@server3
Link : localOut@gnut3 queryreachespeer
Link : queryhit@server3 q_in@gnut3
Link : queryhit@server3 queryhit
Link : query_in query@gnut3
Link : connect_out@gnut3 connect
Link : disconnect_out@gnut3 disconnect
Link : qhit_out@gnut3 queryhit@session3

[session3]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 32,33,50,78,108,128,148,152,185,209,212,259,309,315,324,332,335,343,406,407,414,417,474,508,518,522,527,559,562,566,572,593,623,634,655,657,658,662,696,763,772,782,805,818,827,838,852,852,875,876,899,920,954
whoAmI : 3
TimeToLive : 4

[connector3]
friendlist : 1,0,4,5,6,10,12,13,18,20,22,25,34
whoAmI : 3 

[server3]
capacity : 60


[Peer4]
components : session4@RandomSurfer connector4@ConnectionManager gnut4@Router server4@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session4 in_online@connector4
Link : online@session4 online
Link : offline@session4 in_offline@connector4
Link : out_offline@connector4 offline
Link : query@session4 query_out
Link : query@session4 publish@server4
Link : publish@session4 publish@server4
Link : p_out@server4 publish
Link : link@server4 LinkFind
Link : remove@session4 remove@server4
Link : out_connect@connector4 connect_out
Link : out_disconnect@connector4 disconnect_out
Link : connect_in in_connect@connector4
Link : connect_in connections@gnut4
Link : q_in q_in@gnut4
Link : q_out@gnut4 q_out
Link : localOut@gnut4 peer_in@server4
Link : Link_in peer_in@server4
Link : localOut@gnut4 queryreachespeer
Link : queryhit@server4 q_in@gnut4
Link : queryhit@server4 queryhit
Link : query_in query@gnut4
Link : connect_out@gnut4 connect
Link : disconnect_out@gnut4 disconnect
Link : qhit_out@gnut4 queryhit@session4

[session4]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 9,17,34,36,104,113,166,169,170,187,191,204,213,214,236,237,312,349,363,375,393,426,448,461,486,521,541,572,576,651,655,657,723,752,828,838,858,881,893,893
whoAmI : 4
TimeToLive : 4

[connector4]
friendlist : 1,3,2,6,7,13,17,18,22
whoAmI : 4 

[server4]
capacity : 60


[Peer5]
components : session5@RandomSurfer connector5@ConnectionManager gnut5@Router server5@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session5 in_online@connector5
Link : online@session5 online
Link : offline@session5 in_offline@connector5
Link : out_offline@connector5 offline
Link : query@session5 query_out
Link : query@session5 publish@server5
Link : publish@session5 publish@server5
Link : p_out@server5 publish
Link : link@server5 LinkFind
Link : remove@session5 remove@server5
Link : out_connect@connector5 connect_out
Link : out_disconnect@connector5 disconnect_out
Link : connect_in in_connect@connector5
Link : connect_in connections@gnut5
Link : q_in q_in@gnut5
Link : q_out@gnut5 q_out
Link : localOut@gnut5 peer_in@server5
Link : Link_in peer_in@server5
Link : localOut@gnut5 queryreachespeer
Link : queryhit@server5 q_in@gnut5
Link : queryhit@server5 queryhit
Link : query_in query@gnut5
Link : connect_out@gnut5 connect
Link : disconnect_out@gnut5 disconnect
Link : qhit_out@gnut5 queryhit@session5

[session5]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 60,86,88,117,136,202,206,213,238,239,288,297,297,301,328,338,353,467,524,538,546,547,582,583,605,649,660,699,760,766,773,810,832,836,837,870,917,925,937
whoAmI : 5
TimeToLive : 4

[connector5]
friendlist : 3,12,15,25
whoAmI : 5 

[server5]
capacity : 60


[Peer6]
components : session6@RandomSurfer connector6@ConnectionManager gnut6@Router server6@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session6 in_online@connector6
Link : online@session6 online
Link : offline@session6 in_offline@connector6
Link : out_offline@connector6 offline
Link : query@session6 query_out
Link : query@session6 publish@server6
Link : publish@session6 publish@server6
Link : p_out@server6 publish
Link : link@server6 LinkFind
Link : remove@session6 remove@server6
Link : out_connect@connector6 connect_out
Link : out_disconnect@connector6 disconnect_out
Link : connect_in in_connect@connector6
Link : connect_in connections@gnut6
Link : q_in q_in@gnut6
Link : q_out@gnut6 q_out
Link : localOut@gnut6 peer_in@server6
Link : Link_in peer_in@server6
Link : localOut@gnut6 queryreachespeer
Link : queryhit@server6 q_in@gnut6
Link : queryhit@server6 queryhit
Link : query_in query@gnut6
Link : connect_out@gnut6 connect
Link : disconnect_out@gnut6 disconnect
Link : qhit_out@gnut6 queryhit@session6

[session6]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 12,35,71,110,120,123,134,135,150,165,203,248,255,258,296,362,364,403,409,415,491,494,515,536,537,539,587,619,659,668,746,776,779,780,816,848,856,946
whoAmI : 6
TimeToLive : 4

[connector6]
friendlist : 4,1,2,3,9,13,17,22,24
whoAmI : 6 

[server6]
capacity : 60


[Peer7]
components : session7@RandomSurfer connector7@ConnectionManager gnut7@Router server7@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session7 in_online@connector7
Link : online@session7 online
Link : offline@session7 in_offline@connector7
Link : out_offline@connector7 offline
Link : query@session7 query_out
Link : query@session7 publish@server7
Link : publish@session7 publish@server7
Link : p_out@server7 publish
Link : link@server7 LinkFind
Link : remove@session7 remove@server7
Link : out_connect@connector7 connect_out
Link : out_disconnect@connector7 disconnect_out
Link : connect_in in_connect@connector7
Link : connect_in connections@gnut7
Link : q_in q_in@gnut7
Link : q_out@gnut7 q_out
Link : localOut@gnut7 peer_in@server7
Link : Link_in peer_in@server7
Link : localOut@gnut7 queryreachespeer
Link : queryhit@server7 q_in@gnut7
Link : queryhit@server7 queryhit
Link : query_in query@gnut7
Link : connect_out@gnut7 connect
Link : disconnect_out@gnut7 disconnect
Link : qhit_out@gnut7 queryhit@session7

[session7]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 15,21,28,29,51,53,55,110,139,141,168,193,225,297,345,387,435,437,579,588,589,595,607,620,623,637,690,695,724,797,799
whoAmI : 7
TimeToLive : 4

[connector7]
friendlist : 4,8,10,11,14,19,20,21,23
whoAmI : 7 

[server7]
capacity : 60


[Peer8]
components : session8@RandomSurfer connector8@ConnectionManager gnut8@Router server8@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session8 in_online@connector8
Link : online@session8 online
Link : offline@session8 in_offline@connector8
Link : out_offline@connector8 offline
Link : query@session8 query_out
Link : query@session8 publish@server8
Link : publish@session8 publish@server8
Link : p_out@server8 publish
Link : link@server8 LinkFind
Link : remove@session8 remove@server8
Link : out_connect@connector8 connect_out
Link : out_disconnect@connector8 disconnect_out
Link : connect_in in_connect@connector8
Link : connect_in connections@gnut8
Link : q_in q_in@gnut8
Link : q_out@gnut8 q_out
Link : localOut@gnut8 peer_in@server8
Link : Link_in peer_in@server8
Link : localOut@gnut8 queryreachespeer
Link : queryhit@server8 q_in@gnut8
Link : queryhit@server8 queryhit
Link : query_in query@gnut8
Link : connect_out@gnut8 connect
Link : disconnect_out@gnut8 disconnect
Link : qhit_out@gnut8 queryhit@session8

[session8]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 3,35,92,146,147,180,201,257,291,301,311,338,403,405,458,465,500,514,527,548,585,606,676,689,692,762,796,834,849,888,913,938,952,961
whoAmI : 8
TimeToLive : 4

[connector8]
friendlist : 7,11,19,21,27,31
whoAmI : 8 

[server8]
capacity : 60


[Peer9]
components : session9@RandomSurfer connector9@ConnectionManager gnut9@Router server9@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session9 in_online@connector9
Link : online@session9 online
Link : offline@session9 in_offline@connector9
Link : out_offline@connector9 offline
Link : query@session9 query_out
Link : query@session9 publish@server9
Link : publish@session9 publish@server9
Link : p_out@server9 publish
Link : link@server9 LinkFind
Link : remove@session9 remove@server9
Link : out_connect@connector9 connect_out
Link : out_disconnect@connector9 disconnect_out
Link : connect_in in_connect@connector9
Link : connect_in connections@gnut9
Link : q_in q_in@gnut9
Link : q_out@gnut9 q_out
Link : localOut@gnut9 peer_in@server9
Link : Link_in peer_in@server9
Link : localOut@gnut9 queryreachespeer
Link : queryhit@server9 q_in@gnut9
Link : queryhit@server9 queryhit
Link : query_in query@gnut9
Link : connect_out@gnut9 connect
Link : disconnect_out@gnut9 disconnect
Link : qhit_out@gnut9 queryhit@session9

[session9]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 44,63,68,134,212,273,278,291,304,306,326,357,361,378,397,401,447,451,488,534,567,589,614,629,653,673,677,710,807,863,890,942
whoAmI : 9
TimeToLive : 4

[connector9]
friendlist : 1,6
whoAmI : 9 

[server9]
capacity : 60


[Peer10]
components : session10@RandomSurfer connector10@ConnectionManager gnut10@Router server10@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session10 in_online@connector10
Link : online@session10 online
Link : offline@session10 in_offline@connector10
Link : out_offline@connector10 offline
Link : query@session10 query_out
Link : query@session10 publish@server10
Link : publish@session10 publish@server10
Link : p_out@server10 publish
Link : link@server10 LinkFind
Link : remove@session10 remove@server10
Link : out_connect@connector10 connect_out
Link : out_disconnect@connector10 disconnect_out
Link : connect_in in_connect@connector10
Link : connect_in connections@gnut10
Link : q_in q_in@gnut10
Link : q_out@gnut10 q_out
Link : localOut@gnut10 peer_in@server10
Link : Link_in peer_in@server10
Link : localOut@gnut10 queryreachespeer
Link : queryhit@server10 q_in@gnut10
Link : queryhit@server10 queryhit
Link : query_in query@gnut10
Link : connect_out@gnut10 connect
Link : disconnect_out@gnut10 disconnect
Link : qhit_out@gnut10 queryhit@session10

[session10]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 9,23,43,47,50,52,57,97,107,131,191,194,200,211,264,284,302,355,359,376,395,409,418,425,449,494,512,552,570,605,610,611,665,683,684,718,721,743,771,771,794,802,824,845,846,851,916,944,948
whoAmI : 10
TimeToLive : 4

[connector10]
friendlist : 3,7,20
whoAmI : 10 

[server10]
capacity : 60


[Peer11]
components : session11@RandomSurfer connector11@ConnectionManager gnut11@Router server11@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session11 in_online@connector11
Link : online@session11 online
Link : offline@session11 in_offline@connector11
Link : out_offline@connector11 offline
Link : query@session11 query_out
Link : query@session11 publish@server11
Link : publish@session11 publish@server11
Link : p_out@server11 publish
Link : link@server11 LinkFind
Link : remove@session11 remove@server11
Link : out_connect@connector11 connect_out
Link : out_disconnect@connector11 disconnect_out
Link : connect_in in_connect@connector11
Link : connect_in connections@gnut11
Link : q_in q_in@gnut11
Link : q_out@gnut11 q_out
Link : localOut@gnut11 peer_in@server11
Link : Link_in peer_in@server11
Link : localOut@gnut11 queryreachespeer
Link : queryhit@server11 q_in@gnut11
Link : queryhit@server11 queryhit
Link : query_in query@gnut11
Link : connect_out@gnut11 connect
Link : disconnect_out@gnut11 disconnect
Link : qhit_out@gnut11 queryhit@session11

[session11]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 63,68,75,128,132,160,167,171,182,193,205,230,272,286,308,314,335,370,415,427,452,475,483,493,523,543,543,545,584,612,624,626,697,708,724,763,766,779,800,818,820,868,884
whoAmI : 11
TimeToLive : 4

[connector11]
friendlist : 8,7,19
whoAmI : 11 

[server11]
capacity : 60


[Peer12]
components : session12@RandomSurfer connector12@ConnectionManager gnut12@Router server12@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session12 in_online@connector12
Link : online@session12 online
Link : offline@session12 in_offline@connector12
Link : out_offline@connector12 offline
Link : query@session12 query_out
Link : query@session12 publish@server12
Link : publish@session12 publish@server12
Link : p_out@server12 publish
Link : link@server12 LinkFind
Link : remove@session12 remove@server12
Link : out_connect@connector12 connect_out
Link : out_disconnect@connector12 disconnect_out
Link : connect_in in_connect@connector12
Link : connect_in connections@gnut12
Link : q_in q_in@gnut12
Link : q_out@gnut12 q_out
Link : localOut@gnut12 peer_in@server12
Link : Link_in peer_in@server12
Link : localOut@gnut12 queryreachespeer
Link : queryhit@server12 q_in@gnut12
Link : queryhit@server12 queryhit
Link : query_in query@gnut12
Link : connect_out@gnut12 connect
Link : disconnect_out@gnut12 disconnect
Link : qhit_out@gnut12 queryhit@session12

[session12]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 82,132,150,186,190,236,342,366,398,438,457,468,469,474,489,492,497,501,503,535,561,579,618,619,644,658,669,700,701,714,717,723,767,850,877,878,919,960,964
whoAmI : 12
TimeToLive : 4

[connector12]
friendlist : 5,3,15,25,26,41
whoAmI : 12 

[server12]
capacity : 60


[Peer13]
components : session13@RandomSurfer connector13@ConnectionManager gnut13@Router server13@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session13 in_online@connector13
Link : online@session13 online
Link : offline@session13 in_offline@connector13
Link : out_offline@connector13 offline
Link : query@session13 query_out
Link : query@session13 publish@server13
Link : publish@session13 publish@server13
Link : p_out@server13 publish
Link : link@server13 LinkFind
Link : remove@session13 remove@server13
Link : out_connect@connector13 connect_out
Link : out_disconnect@connector13 disconnect_out
Link : connect_in in_connect@connector13
Link : connect_in connections@gnut13
Link : q_in q_in@gnut13
Link : q_out@gnut13 q_out
Link : localOut@gnut13 peer_in@server13
Link : Link_in peer_in@server13
Link : localOut@gnut13 queryreachespeer
Link : queryhit@server13 q_in@gnut13
Link : queryhit@server13 queryhit
Link : query_in query@gnut13
Link : connect_out@gnut13 connect
Link : disconnect_out@gnut13 disconnect
Link : qhit_out@gnut13 queryhit@session13

[session13]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 41,51,79,101,133,214,257,303,393,431,508,529,549,551,560,576,580,584,590,632,647,661,663,687,707,752,777,804,817,891,896,918,944,958
whoAmI : 13
TimeToLive : 4

[connector13]
friendlist : 1,6,4,3,16,43
whoAmI : 13 

[server13]
capacity : 60


[Peer14]
components : session14@RandomSurfer connector14@ConnectionManager gnut14@Router server14@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session14 in_online@connector14
Link : online@session14 online
Link : offline@session14 in_offline@connector14
Link : out_offline@connector14 offline
Link : query@session14 query_out
Link : query@session14 publish@server14
Link : publish@session14 publish@server14
Link : p_out@server14 publish
Link : link@server14 LinkFind
Link : remove@session14 remove@server14
Link : out_connect@connector14 connect_out
Link : out_disconnect@connector14 disconnect_out
Link : connect_in in_connect@connector14
Link : connect_in connections@gnut14
Link : q_in q_in@gnut14
Link : q_out@gnut14 q_out
Link : localOut@gnut14 peer_in@server14
Link : Link_in peer_in@server14
Link : localOut@gnut14 queryreachespeer
Link : queryhit@server14 q_in@gnut14
Link : queryhit@server14 queryhit
Link : query_in query@gnut14
Link : connect_out@gnut14 connect
Link : disconnect_out@gnut14 disconnect
Link : qhit_out@gnut14 queryhit@session14

[session14]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 1,13,65,74,80,89,108,161,161,182,226,281,319,352,368,429,434,439,449,462,477,498,541,592,620,625,631,639,698,715,742,745,768,887,943
whoAmI : 14
TimeToLive : 4

[connector14]
friendlist : 7,23
whoAmI : 14 

[server14]
capacity : 60


[Peer15]
components : session15@RandomSurfer connector15@ConnectionManager gnut15@Router server15@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session15 in_online@connector15
Link : online@session15 online
Link : offline@session15 in_offline@connector15
Link : out_offline@connector15 offline
Link : query@session15 query_out
Link : query@session15 publish@server15
Link : publish@session15 publish@server15
Link : p_out@server15 publish
Link : link@server15 LinkFind
Link : remove@session15 remove@server15
Link : out_connect@connector15 connect_out
Link : out_disconnect@connector15 disconnect_out
Link : connect_in in_connect@connector15
Link : connect_in connections@gnut15
Link : q_in q_in@gnut15
Link : q_out@gnut15 q_out
Link : localOut@gnut15 peer_in@server15
Link : Link_in peer_in@server15
Link : localOut@gnut15 queryreachespeer
Link : queryhit@server15 q_in@gnut15
Link : queryhit@server15 queryhit
Link : query_in query@gnut15
Link : connect_out@gnut15 connect
Link : disconnect_out@gnut15 disconnect
Link : qhit_out@gnut15 queryhit@session15

[session15]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 24,106,112,119,126,130,169,223,224,239,252,295,304,305,312,388,445,513,526,549,551,560,577,602,615,627,633,640,644,647,670,672,675,682,690,733,770,799,829,833,897,907,914,947
whoAmI : 15
TimeToLive : 4

[connector15]
friendlist : 12,5,25,30
whoAmI : 15 

[server15]
capacity : 60


[Peer16]
components : session16@RandomSurfer connector16@ConnectionManager gnut16@Router server16@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session16 in_online@connector16
Link : online@session16 online
Link : offline@session16 in_offline@connector16
Link : out_offline@connector16 offline
Link : query@session16 query_out
Link : query@session16 publish@server16
Link : publish@session16 publish@server16
Link : p_out@server16 publish
Link : link@server16 LinkFind
Link : remove@session16 remove@server16
Link : out_connect@connector16 connect_out
Link : out_disconnect@connector16 disconnect_out
Link : connect_in in_connect@connector16
Link : connect_in connections@gnut16
Link : q_in q_in@gnut16
Link : q_out@gnut16 q_out
Link : localOut@gnut16 peer_in@server16
Link : Link_in peer_in@server16
Link : localOut@gnut16 queryreachespeer
Link : queryhit@server16 q_in@gnut16
Link : queryhit@server16 queryhit
Link : query_in query@gnut16
Link : connect_out@gnut16 connect
Link : disconnect_out@gnut16 disconnect
Link : qhit_out@gnut16 queryhit@session16

[session16]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 23,53,61,76,79,99,145,155,210,220,275,281,307,316,339,371,391,416,421,446,463,472,516,530,542,577,599,600,704,706,738,803,826,857,885,901,928,955
whoAmI : 16
TimeToLive : 4

[connector16]
friendlist : 1,13,43
whoAmI : 16 

[server16]
capacity : 60


[Peer17]
components : session17@RandomSurfer connector17@ConnectionManager gnut17@Router server17@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session17 in_online@connector17
Link : online@session17 online
Link : offline@session17 in_offline@connector17
Link : out_offline@connector17 offline
Link : query@session17 query_out
Link : query@session17 publish@server17
Link : publish@session17 publish@server17
Link : p_out@server17 publish
Link : link@server17 LinkFind
Link : remove@session17 remove@server17
Link : out_connect@connector17 connect_out
Link : out_disconnect@connector17 disconnect_out
Link : connect_in in_connect@connector17
Link : connect_in connections@gnut17
Link : q_in q_in@gnut17
Link : q_out@gnut17 q_out
Link : localOut@gnut17 peer_in@server17
Link : Link_in peer_in@server17
Link : localOut@gnut17 queryreachespeer
Link : queryhit@server17 q_in@gnut17
Link : queryhit@server17 queryhit
Link : query_in query@gnut17
Link : connect_out@gnut17 connect
Link : disconnect_out@gnut17 disconnect
Link : qhit_out@gnut17 queryhit@session17

[session17]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 4,33,46,64,87,93,118,139,155,252,273,287,293,382,384,390,396,403,406,443,486,504,520,528,546,616,635,654,773,777,814,864,869,908,957
whoAmI : 17
TimeToLive : 4

[connector17]
friendlist : 4,6,37,48
whoAmI : 17 

[server17]
capacity : 60


[Peer18]
components : session18@RandomSurfer connector18@ConnectionManager gnut18@Router server18@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session18 in_online@connector18
Link : online@session18 online
Link : offline@session18 in_offline@connector18
Link : out_offline@connector18 offline
Link : query@session18 query_out
Link : query@session18 publish@server18
Link : publish@session18 publish@server18
Link : p_out@server18 publish
Link : link@server18 LinkFind
Link : remove@session18 remove@server18
Link : out_connect@connector18 connect_out
Link : out_disconnect@connector18 disconnect_out
Link : connect_in in_connect@connector18
Link : connect_in connections@gnut18
Link : q_in q_in@gnut18
Link : q_out@gnut18 q_out
Link : localOut@gnut18 peer_in@server18
Link : Link_in peer_in@server18
Link : localOut@gnut18 queryreachespeer
Link : queryhit@server18 q_in@gnut18
Link : queryhit@server18 queryhit
Link : query_in query@gnut18
Link : connect_out@gnut18 connect
Link : disconnect_out@gnut18 disconnect
Link : qhit_out@gnut18 queryhit@session18

[session18]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 12,22,76,115,123,163,164,219,256,260,318,322,324,325,397,410,429,443,467,483,487,494,503,529,555,559,587,603,620,633,685,697,781,822,854,901,905
whoAmI : 18
TimeToLive : 4

[connector18]
friendlist : 4,3,28,29
whoAmI : 18 

[server18]
capacity : 60


[Peer19]
components : session19@RandomSurfer connector19@ConnectionManager gnut19@Router server19@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session19 in_online@connector19
Link : online@session19 online
Link : offline@session19 in_offline@connector19
Link : out_offline@connector19 offline
Link : query@session19 query_out
Link : query@session19 publish@server19
Link : publish@session19 publish@server19
Link : p_out@server19 publish
Link : link@server19 LinkFind
Link : remove@session19 remove@server19
Link : out_connect@connector19 connect_out
Link : out_disconnect@connector19 disconnect_out
Link : connect_in in_connect@connector19
Link : connect_in connections@gnut19
Link : q_in q_in@gnut19
Link : q_out@gnut19 q_out
Link : localOut@gnut19 peer_in@server19
Link : Link_in peer_in@server19
Link : localOut@gnut19 queryreachespeer
Link : queryhit@server19 q_in@gnut19
Link : queryhit@server19 queryhit
Link : query_in query@gnut19
Link : connect_out@gnut19 connect
Link : disconnect_out@gnut19 disconnect
Link : qhit_out@gnut19 queryhit@session19

[session19]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 54,66,69,99,117,151,160,185,221,323,344,396,427,442,446,476,490,498,506,510,550,557,606,636,646,647,650,660,676,703,722,732,733,734,764,791,819,821,837,839,840,847,853,862,882,921,934,940
whoAmI : 19
TimeToLive : 4

[connector19]
friendlist : 11,8,7,27,31
whoAmI : 19 

[server19]
capacity : 60


[Peer20]
components : session20@RandomSurfer connector20@ConnectionManager gnut20@Router server20@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session20 in_online@connector20
Link : online@session20 online
Link : offline@session20 in_offline@connector20
Link : out_offline@connector20 offline
Link : query@session20 query_out
Link : query@session20 publish@server20
Link : publish@session20 publish@server20
Link : p_out@server20 publish
Link : link@server20 LinkFind
Link : remove@session20 remove@server20
Link : out_connect@connector20 connect_out
Link : out_disconnect@connector20 disconnect_out
Link : connect_in in_connect@connector20
Link : connect_in connections@gnut20
Link : q_in q_in@gnut20
Link : q_out@gnut20 q_out
Link : localOut@gnut20 peer_in@server20
Link : Link_in peer_in@server20
Link : localOut@gnut20 queryreachespeer
Link : queryhit@server20 q_in@gnut20
Link : queryhit@server20 queryhit
Link : query_in query@gnut20
Link : connect_out@gnut20 connect
Link : disconnect_out@gnut20 disconnect
Link : qhit_out@gnut20 queryhit@session20

[session20]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 7,29,63,82,100,142,172,187,192,206,210,233,241,379,418,421,454,476,483,491,504,516,560,600,630,681,684,713,716,719,769,785,794,804,886,912,912,923,936
whoAmI : 20
TimeToLive : 4

[connector20]
friendlist : 10,3,7
whoAmI : 20 

[server20]
capacity : 60


[Peer21]
components : session21@RandomSurfer connector21@ConnectionManager gnut21@Router server21@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session21 in_online@connector21
Link : online@session21 online
Link : offline@session21 in_offline@connector21
Link : out_offline@connector21 offline
Link : query@session21 query_out
Link : query@session21 publish@server21
Link : publish@session21 publish@server21
Link : p_out@server21 publish
Link : link@server21 LinkFind
Link : remove@session21 remove@server21
Link : out_connect@connector21 connect_out
Link : out_disconnect@connector21 disconnect_out
Link : connect_in in_connect@connector21
Link : connect_in connections@gnut21
Link : q_in q_in@gnut21
Link : q_out@gnut21 q_out
Link : localOut@gnut21 peer_in@server21
Link : Link_in peer_in@server21
Link : localOut@gnut21 queryreachespeer
Link : queryhit@server21 q_in@gnut21
Link : queryhit@server21 queryhit
Link : query_in query@gnut21
Link : connect_out@gnut21 connect
Link : disconnect_out@gnut21 disconnect
Link : qhit_out@gnut21 queryhit@session21

[session21]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 54,56,64,79,103,105,118,121,182,194,251,254,263,277,283,330,331,334,355,423,463,499,550,565,628,632,656,707,734,749,829,888,906,908,919,927,930,932,962,964
whoAmI : 21
TimeToLive : 4

[connector21]
friendlist : 8,7,36,45
whoAmI : 21 

[server21]
capacity : 60


[Peer22]
components : session22@RandomSurfer connector22@ConnectionManager gnut22@Router server22@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session22 in_online@connector22
Link : online@session22 online
Link : offline@session22 in_offline@connector22
Link : out_offline@connector22 offline
Link : query@session22 query_out
Link : query@session22 publish@server22
Link : publish@session22 publish@server22
Link : p_out@server22 publish
Link : link@server22 LinkFind
Link : remove@session22 remove@server22
Link : out_connect@connector22 connect_out
Link : out_disconnect@connector22 disconnect_out
Link : connect_in in_connect@connector22
Link : connect_in connections@gnut22
Link : q_in q_in@gnut22
Link : q_out@gnut22 q_out
Link : localOut@gnut22 peer_in@server22
Link : Link_in peer_in@server22
Link : localOut@gnut22 queryreachespeer
Link : queryhit@server22 q_in@gnut22
Link : queryhit@server22 queryhit
Link : query_in query@gnut22
Link : connect_out@gnut22 connect
Link : disconnect_out@gnut22 disconnect
Link : qhit_out@gnut22 queryhit@session22

[session22]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 15,33,37,56,95,154,183,269,300,331,341,344,372,400,416,459,471,482,525,533,540,556,564,597,603,626,652,690,739,747,763,801,861,864,865,897,918,929,933,938
whoAmI : 22
TimeToLive : 4

[connector22]
friendlist : 3,6,4
whoAmI : 22 

[server22]
capacity : 60


[Peer23]
components : session23@RandomSurfer connector23@ConnectionManager gnut23@Router server23@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session23 in_online@connector23
Link : online@session23 online
Link : offline@session23 in_offline@connector23
Link : out_offline@connector23 offline
Link : query@session23 query_out
Link : query@session23 publish@server23
Link : publish@session23 publish@server23
Link : p_out@server23 publish
Link : link@server23 LinkFind
Link : remove@session23 remove@server23
Link : out_connect@connector23 connect_out
Link : out_disconnect@connector23 disconnect_out
Link : connect_in in_connect@connector23
Link : connect_in connections@gnut23
Link : q_in q_in@gnut23
Link : q_out@gnut23 q_out
Link : localOut@gnut23 peer_in@server23
Link : Link_in peer_in@server23
Link : localOut@gnut23 queryreachespeer
Link : queryhit@server23 q_in@gnut23
Link : queryhit@server23 queryhit
Link : query_in query@gnut23
Link : connect_out@gnut23 connect
Link : disconnect_out@gnut23 disconnect
Link : qhit_out@gnut23 queryhit@session23

[session23]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 6,10,19,36,45,52,62,77,112,115,118,129,138,148,168,189,203,207,222,227,233,314,332,332,354,441,464,475,489,511,539,558,566,585,677,722,747,752,756,776,785,790,802,825,841,869,872,882,897,927
whoAmI : 23
TimeToLive : 4

[connector23]
friendlist : 14,7,46
whoAmI : 23 

[server23]
capacity : 60


[Peer24]
components : session24@RandomSurfer connector24@ConnectionManager gnut24@Router server24@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session24 in_online@connector24
Link : online@session24 online
Link : offline@session24 in_offline@connector24
Link : out_offline@connector24 offline
Link : query@session24 query_out
Link : query@session24 publish@server24
Link : publish@session24 publish@server24
Link : p_out@server24 publish
Link : link@server24 LinkFind
Link : remove@session24 remove@server24
Link : out_connect@connector24 connect_out
Link : out_disconnect@connector24 disconnect_out
Link : connect_in in_connect@connector24
Link : connect_in connections@gnut24
Link : q_in q_in@gnut24
Link : q_out@gnut24 q_out
Link : localOut@gnut24 peer_in@server24
Link : Link_in peer_in@server24
Link : localOut@gnut24 queryreachespeer
Link : queryhit@server24 q_in@gnut24
Link : queryhit@server24 queryhit
Link : query_in query@gnut24
Link : connect_out@gnut24 connect
Link : disconnect_out@gnut24 disconnect
Link : qhit_out@gnut24 queryhit@session24

[session24]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 3,6,62,72,174,217,229,247,294,390,448,470,502,568,571,587,599,604,607,653,713,821,827,879,936
whoAmI : 24
TimeToLive : 4

[connector24]
friendlist : 6
whoAmI : 24 

[server24]
capacity : 60


[Peer25]
components : session25@RandomSurfer connector25@ConnectionManager gnut25@Router server25@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session25 in_online@connector25
Link : online@session25 online
Link : offline@session25 in_offline@connector25
Link : out_offline@connector25 offline
Link : query@session25 query_out
Link : query@session25 publish@server25
Link : publish@session25 publish@server25
Link : p_out@server25 publish
Link : link@server25 LinkFind
Link : remove@session25 remove@server25
Link : out_connect@connector25 connect_out
Link : out_disconnect@connector25 disconnect_out
Link : connect_in in_connect@connector25
Link : connect_in connections@gnut25
Link : q_in q_in@gnut25
Link : q_out@gnut25 q_out
Link : localOut@gnut25 peer_in@server25
Link : Link_in peer_in@server25
Link : localOut@gnut25 queryreachespeer
Link : queryhit@server25 q_in@gnut25
Link : queryhit@server25 queryhit
Link : query_in query@gnut25
Link : connect_out@gnut25 connect
Link : disconnect_out@gnut25 disconnect
Link : qhit_out@gnut25 queryhit@session25

[session25]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 106,130,137,162,172,173,176,244,285,294,298,316,357,424,484,556,568,601,624,650,872,895,936,959,962
whoAmI : 25
TimeToLive : 4

[connector25]
friendlist : 12,3,5,15,30,41
whoAmI : 25 

[server25]
capacity : 60


[Peer26]
components : session26@RandomSurfer connector26@ConnectionManager gnut26@Router server26@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session26 in_online@connector26
Link : online@session26 online
Link : offline@session26 in_offline@connector26
Link : out_offline@connector26 offline
Link : query@session26 query_out
Link : query@session26 publish@server26
Link : publish@session26 publish@server26
Link : p_out@server26 publish
Link : link@server26 LinkFind
Link : remove@session26 remove@server26
Link : out_connect@connector26 connect_out
Link : out_disconnect@connector26 disconnect_out
Link : connect_in in_connect@connector26
Link : connect_in connections@gnut26
Link : q_in q_in@gnut26
Link : q_out@gnut26 q_out
Link : localOut@gnut26 peer_in@server26
Link : Link_in peer_in@server26
Link : localOut@gnut26 queryreachespeer
Link : queryhit@server26 q_in@gnut26
Link : queryhit@server26 queryhit
Link : query_in query@gnut26
Link : connect_out@gnut26 connect
Link : disconnect_out@gnut26 disconnect
Link : qhit_out@gnut26 queryhit@session26

[session26]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 8,26,32,40,57,66,87,154,196,247,279,280,293,327,337,353,365,435,461,471,480,517,534,552,602,611,670,691,701,705,786,789,792,801,805,831,855,872,906,911,950,956
whoAmI : 26
TimeToLive : 4

[connector26]
friendlist : 12,33,38
whoAmI : 26 

[server26]
capacity : 60


[Peer27]
components : session27@RandomSurfer connector27@ConnectionManager gnut27@Router server27@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session27 in_online@connector27
Link : online@session27 online
Link : offline@session27 in_offline@connector27
Link : out_offline@connector27 offline
Link : query@session27 query_out
Link : query@session27 publish@server27
Link : publish@session27 publish@server27
Link : p_out@server27 publish
Link : link@server27 LinkFind
Link : remove@session27 remove@server27
Link : out_connect@connector27 connect_out
Link : out_disconnect@connector27 disconnect_out
Link : connect_in in_connect@connector27
Link : connect_in connections@gnut27
Link : q_in q_in@gnut27
Link : q_out@gnut27 q_out
Link : localOut@gnut27 peer_in@server27
Link : Link_in peer_in@server27
Link : localOut@gnut27 queryreachespeer
Link : queryhit@server27 q_in@gnut27
Link : queryhit@server27 queryhit
Link : query_in query@gnut27
Link : connect_out@gnut27 connect
Link : disconnect_out@gnut27 disconnect
Link : qhit_out@gnut27 queryhit@session27

[session27]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 7,21,47,49,56,67,67,90,129,143,156,158,164,195,206,225,248,256,259,307,311,343,346,348,362,383,386,391,399,410,411,528,537,559,571,579,585,604,657,693,712,720,780,782,844,896,905,910,918,933
whoAmI : 27
TimeToLive : 4

[connector27]
friendlist : 8,19,28,31
whoAmI : 27 

[server27]
capacity : 60


[Peer28]
components : session28@RandomSurfer connector28@ConnectionManager gnut28@Router server28@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session28 in_online@connector28
Link : online@session28 online
Link : offline@session28 in_offline@connector28
Link : out_offline@connector28 offline
Link : query@session28 query_out
Link : query@session28 publish@server28
Link : publish@session28 publish@server28
Link : p_out@server28 publish
Link : link@server28 LinkFind
Link : remove@session28 remove@server28
Link : out_connect@connector28 connect_out
Link : out_disconnect@connector28 disconnect_out
Link : connect_in in_connect@connector28
Link : connect_in connections@gnut28
Link : q_in q_in@gnut28
Link : q_out@gnut28 q_out
Link : localOut@gnut28 peer_in@server28
Link : Link_in peer_in@server28
Link : localOut@gnut28 queryreachespeer
Link : queryhit@server28 q_in@gnut28
Link : queryhit@server28 queryhit
Link : query_in query@gnut28
Link : connect_out@gnut28 connect
Link : disconnect_out@gnut28 disconnect
Link : qhit_out@gnut28 queryhit@session28

[session28]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 58,73,87,102,110,198,204,217,218,221,221,245,270,281,308,375,413,431,447,473,515,521,544,553,568,604,608,640,653,674,678,679,802,812,862,882,889,925,925,952,959,965
whoAmI : 28
TimeToLive : 4

[connector28]
friendlist : 27,18,29
whoAmI : 28 

[server28]
capacity : 60


[Peer29]
components : session29@RandomSurfer connector29@ConnectionManager gnut29@Router server29@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session29 in_online@connector29
Link : online@session29 online
Link : offline@session29 in_offline@connector29
Link : out_offline@connector29 offline
Link : query@session29 query_out
Link : query@session29 publish@server29
Link : publish@session29 publish@server29
Link : p_out@server29 publish
Link : link@server29 LinkFind
Link : remove@session29 remove@server29
Link : out_connect@connector29 connect_out
Link : out_disconnect@connector29 disconnect_out
Link : connect_in in_connect@connector29
Link : connect_in connections@gnut29
Link : q_in q_in@gnut29
Link : q_out@gnut29 q_out
Link : localOut@gnut29 peer_in@server29
Link : Link_in peer_in@server29
Link : localOut@gnut29 queryreachespeer
Link : queryhit@server29 q_in@gnut29
Link : queryhit@server29 queryhit
Link : query_in query@gnut29
Link : connect_out@gnut29 connect
Link : disconnect_out@gnut29 disconnect
Link : qhit_out@gnut29 queryhit@session29

[session29]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 16,53,65,229,263,266,280,354,374,400,433,472,510,555,558,583,597,611,624,631,682,703,743,751,764,783,799,800,808,833,885,926,940,962
whoAmI : 29
TimeToLive : 4

[connector29]
friendlist : 18,28
whoAmI : 29 

[server29]
capacity : 60


[Peer30]
components : session30@RandomSurfer connector30@ConnectionManager gnut30@Router server30@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session30 in_online@connector30
Link : online@session30 online
Link : offline@session30 in_offline@connector30
Link : out_offline@connector30 offline
Link : query@session30 query_out
Link : query@session30 publish@server30
Link : publish@session30 publish@server30
Link : p_out@server30 publish
Link : link@server30 LinkFind
Link : remove@session30 remove@server30
Link : out_connect@connector30 connect_out
Link : out_disconnect@connector30 disconnect_out
Link : connect_in in_connect@connector30
Link : connect_in connections@gnut30
Link : q_in q_in@gnut30
Link : q_out@gnut30 q_out
Link : localOut@gnut30 peer_in@server30
Link : Link_in peer_in@server30
Link : localOut@gnut30 queryreachespeer
Link : queryhit@server30 q_in@gnut30
Link : queryhit@server30 queryhit
Link : query_in query@gnut30
Link : connect_out@gnut30 connect
Link : disconnect_out@gnut30 disconnect
Link : qhit_out@gnut30 queryhit@session30

[session30]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 64,69,74,85,93,94,131,136,147,151,199,205,207,255,296,310,388,404,442,456,462,470,481,495,543,578,643,646,689,698,702,704,725,742,748,757,778,813,836,881,887,889,906
whoAmI : 30
TimeToLive : 4

[connector30]
friendlist : 15,25,41
whoAmI : 30 

[server30]
capacity : 60


[Peer31]
components : session31@RandomSurfer connector31@ConnectionManager gnut31@Router server31@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session31 in_online@connector31
Link : online@session31 online
Link : offline@session31 in_offline@connector31
Link : out_offline@connector31 offline
Link : query@session31 query_out
Link : query@session31 publish@server31
Link : publish@session31 publish@server31
Link : p_out@server31 publish
Link : link@server31 LinkFind
Link : remove@session31 remove@server31
Link : out_connect@connector31 connect_out
Link : out_disconnect@connector31 disconnect_out
Link : connect_in in_connect@connector31
Link : connect_in connections@gnut31
Link : q_in q_in@gnut31
Link : q_out@gnut31 q_out
Link : localOut@gnut31 peer_in@server31
Link : Link_in peer_in@server31
Link : localOut@gnut31 queryreachespeer
Link : queryhit@server31 q_in@gnut31
Link : queryhit@server31 queryhit
Link : query_in query@gnut31
Link : connect_out@gnut31 connect
Link : disconnect_out@gnut31 disconnect
Link : qhit_out@gnut31 queryhit@session31

[session31]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 10,11,109,137,141,149,156,177,188,207,214,218,261,283,338,345,367,384,484,487,501,517,517,539,564,570,625,669,683,695,703,740,744,809,828,843,866,892,894,898,900
whoAmI : 31
TimeToLive : 4

[connector31]
friendlist : 27,8,19
whoAmI : 31 

[server31]
capacity : 60


[Peer32]
components : session32@RandomSurfer connector32@ConnectionManager gnut32@Router server32@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session32 in_online@connector32
Link : online@session32 online
Link : offline@session32 in_offline@connector32
Link : out_offline@connector32 offline
Link : query@session32 query_out
Link : query@session32 publish@server32
Link : publish@session32 publish@server32
Link : p_out@server32 publish
Link : link@server32 LinkFind
Link : remove@session32 remove@server32
Link : out_connect@connector32 connect_out
Link : out_disconnect@connector32 disconnect_out
Link : connect_in in_connect@connector32
Link : connect_in connections@gnut32
Link : q_in q_in@gnut32
Link : q_out@gnut32 q_out
Link : localOut@gnut32 peer_in@server32
Link : Link_in peer_in@server32
Link : localOut@gnut32 queryreachespeer
Link : queryhit@server32 q_in@gnut32
Link : queryhit@server32 queryhit
Link : query_in query@gnut32
Link : connect_out@gnut32 connect
Link : disconnect_out@gnut32 disconnect
Link : qhit_out@gnut32 queryhit@session32

[session32]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 6,36,77,189,230,233,273,287,300,317,368,390,394,407,409,413,423,450,526,551,558,594,598,609,650,654,655,668,675,687,687,744,760,779,781,795,859,863,871,873,950
whoAmI : 32
TimeToLive : 4

[connector32]
friendlist : 0,40
whoAmI : 32 

[server32]
capacity : 60


[Peer33]
components : session33@RandomSurfer connector33@ConnectionManager gnut33@Router server33@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session33 in_online@connector33
Link : online@session33 online
Link : offline@session33 in_offline@connector33
Link : out_offline@connector33 offline
Link : query@session33 query_out
Link : query@session33 publish@server33
Link : publish@session33 publish@server33
Link : p_out@server33 publish
Link : link@server33 LinkFind
Link : remove@session33 remove@server33
Link : out_connect@connector33 connect_out
Link : out_disconnect@connector33 disconnect_out
Link : connect_in in_connect@connector33
Link : connect_in connections@gnut33
Link : q_in q_in@gnut33
Link : q_out@gnut33 q_out
Link : localOut@gnut33 peer_in@server33
Link : Link_in peer_in@server33
Link : localOut@gnut33 queryreachespeer
Link : queryhit@server33 q_in@gnut33
Link : queryhit@server33 queryhit
Link : query_in query@gnut33
Link : connect_out@gnut33 connect
Link : disconnect_out@gnut33 disconnect
Link : qhit_out@gnut33 queryhit@session33

[session33]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 11,35,49,96,150,160,162,179,230,313,317,325,359,369,389,405,414,418,420,436,522,569,570,586,615,616,645,697,718,765,775,803,828,886,920
whoAmI : 33
TimeToLive : 4

[connector33]
friendlist : 26,35
whoAmI : 33 

[server33]
capacity : 60


[Peer34]
components : session34@RandomSurfer connector34@ConnectionManager gnut34@Router server34@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session34 in_online@connector34
Link : online@session34 online
Link : offline@session34 in_offline@connector34
Link : out_offline@connector34 offline
Link : query@session34 query_out
Link : query@session34 publish@server34
Link : publish@session34 publish@server34
Link : p_out@server34 publish
Link : link@server34 LinkFind
Link : remove@session34 remove@server34
Link : out_connect@connector34 connect_out
Link : out_disconnect@connector34 disconnect_out
Link : connect_in in_connect@connector34
Link : connect_in connections@gnut34
Link : q_in q_in@gnut34
Link : q_out@gnut34 q_out
Link : localOut@gnut34 peer_in@server34
Link : Link_in peer_in@server34
Link : localOut@gnut34 queryreachespeer
Link : queryhit@server34 q_in@gnut34
Link : queryhit@server34 queryhit
Link : query_in query@gnut34
Link : connect_out@gnut34 connect
Link : disconnect_out@gnut34 disconnect
Link : qhit_out@gnut34 queryhit@session34

[session34]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 5,22,24,25,26,38,41,44,71,71,82,98,114,131,170,201,231,232,249,268,288,300,311,326,334,341,363,372,378,402,408,432,437,459,470,507,562,576,596,612,654,693,702,705,730,770,774,786,830,836,848,953
whoAmI : 34
TimeToLive : 4

[connector34]
friendlist : 3
whoAmI : 34 

[server34]
capacity : 60


[Peer35]
components : session35@RandomSurfer connector35@ConnectionManager gnut35@Router server35@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session35 in_online@connector35
Link : online@session35 online
Link : offline@session35 in_offline@connector35
Link : out_offline@connector35 offline
Link : query@session35 query_out
Link : query@session35 publish@server35
Link : publish@session35 publish@server35
Link : p_out@server35 publish
Link : link@server35 LinkFind
Link : remove@session35 remove@server35
Link : out_connect@connector35 connect_out
Link : out_disconnect@connector35 disconnect_out
Link : connect_in in_connect@connector35
Link : connect_in connections@gnut35
Link : q_in q_in@gnut35
Link : q_out@gnut35 q_out
Link : localOut@gnut35 peer_in@server35
Link : Link_in peer_in@server35
Link : localOut@gnut35 queryreachespeer
Link : queryhit@server35 q_in@gnut35
Link : queryhit@server35 queryhit
Link : query_in query@gnut35
Link : connect_out@gnut35 connect
Link : disconnect_out@gnut35 disconnect
Link : qhit_out@gnut35 queryhit@session35

[session35]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 46,120,122,148,153,184,216,217,234,243,246,250,284,289,313,391,436,440,553,563,566,671,728,741,753,789,793,794,806,845,857,931,941
whoAmI : 35
TimeToLive : 4

[connector35]
friendlist : 33
whoAmI : 35 

[server35]
capacity : 60


[Peer36]
components : session36@RandomSurfer connector36@ConnectionManager gnut36@Router server36@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session36 in_online@connector36
Link : online@session36 online
Link : offline@session36 in_offline@connector36
Link : out_offline@connector36 offline
Link : query@session36 query_out
Link : query@session36 publish@server36
Link : publish@session36 publish@server36
Link : p_out@server36 publish
Link : link@server36 LinkFind
Link : remove@session36 remove@server36
Link : out_connect@connector36 connect_out
Link : out_disconnect@connector36 disconnect_out
Link : connect_in in_connect@connector36
Link : connect_in connections@gnut36
Link : q_in q_in@gnut36
Link : q_out@gnut36 q_out
Link : localOut@gnut36 peer_in@server36
Link : Link_in peer_in@server36
Link : localOut@gnut36 queryreachespeer
Link : queryhit@server36 q_in@gnut36
Link : queryhit@server36 queryhit
Link : query_in query@gnut36
Link : connect_out@gnut36 connect
Link : disconnect_out@gnut36 disconnect
Link : qhit_out@gnut36 queryhit@session36

[session36]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 4,10,18,31,58,88,90,98,111,184,196,197,274,276,285,336,378,392,412,439,488,520,522,554,578,594,688,694,700,706,712,736,754,755,755,780,784,788,832,835,866,867,880,939,951,951,956
whoAmI : 36
TimeToLive : 4

[connector36]
friendlist : 21,39,44,45
whoAmI : 36 

[server36]
capacity : 60


[Peer37]
components : session37@RandomSurfer connector37@ConnectionManager gnut37@Router server37@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session37 in_online@connector37
Link : online@session37 online
Link : offline@session37 in_offline@connector37
Link : out_offline@connector37 offline
Link : query@session37 query_out
Link : query@session37 publish@server37
Link : publish@session37 publish@server37
Link : p_out@server37 publish
Link : link@server37 LinkFind
Link : remove@session37 remove@server37
Link : out_connect@connector37 connect_out
Link : out_disconnect@connector37 disconnect_out
Link : connect_in in_connect@connector37
Link : connect_in connections@gnut37
Link : q_in q_in@gnut37
Link : q_out@gnut37 q_out
Link : localOut@gnut37 peer_in@server37
Link : Link_in peer_in@server37
Link : localOut@gnut37 queryreachespeer
Link : queryhit@server37 q_in@gnut37
Link : queryhit@server37 queryhit
Link : query_in query@gnut37
Link : connect_out@gnut37 connect
Link : disconnect_out@gnut37 disconnect
Link : qhit_out@gnut37 queryhit@session37

[session37]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 16,101,102,211,215,282,285,293,298,299,340,356,371,381,382,389,400,414,441,466,476,542,581,582,591,619,679,684,713,727,787,815,823,875,879
whoAmI : 37
TimeToLive : 4

[connector37]
friendlist : 17,48
whoAmI : 37 

[server37]
capacity : 60


[Peer38]
components : session38@RandomSurfer connector38@ConnectionManager gnut38@Router server38@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session38 in_online@connector38
Link : online@session38 online
Link : offline@session38 in_offline@connector38
Link : out_offline@connector38 offline
Link : query@session38 query_out
Link : query@session38 publish@server38
Link : publish@session38 publish@server38
Link : p_out@server38 publish
Link : link@server38 LinkFind
Link : remove@session38 remove@server38
Link : out_connect@connector38 connect_out
Link : out_disconnect@connector38 disconnect_out
Link : connect_in in_connect@connector38
Link : connect_in connections@gnut38
Link : q_in q_in@gnut38
Link : q_out@gnut38 q_out
Link : localOut@gnut38 peer_in@server38
Link : Link_in peer_in@server38
Link : localOut@gnut38 queryreachespeer
Link : queryhit@server38 q_in@gnut38
Link : queryhit@server38 queryhit
Link : query_in query@gnut38
Link : connect_out@gnut38 connect
Link : disconnect_out@gnut38 disconnect
Link : qhit_out@gnut38 queryhit@session38

[session38]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 15,66,113,143,163,163,192,199,251,307,328,342,370,392,392,417,423,437,489,506,533,584,613,623,659,664,678,714,737,758,792,843,874,908,920,933,965
whoAmI : 38
TimeToLive : 4

[connector38]
friendlist : 26
whoAmI : 38 

[server38]
capacity : 60


[Peer39]
components : session39@RandomSurfer connector39@ConnectionManager gnut39@Router server39@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session39 in_online@connector39
Link : online@session39 online
Link : offline@session39 in_offline@connector39
Link : out_offline@connector39 offline
Link : query@session39 query_out
Link : query@session39 publish@server39
Link : publish@session39 publish@server39
Link : p_out@server39 publish
Link : link@server39 LinkFind
Link : remove@session39 remove@server39
Link : out_connect@connector39 connect_out
Link : out_disconnect@connector39 disconnect_out
Link : connect_in in_connect@connector39
Link : connect_in connections@gnut39
Link : q_in q_in@gnut39
Link : q_out@gnut39 q_out
Link : localOut@gnut39 peer_in@server39
Link : Link_in peer_in@server39
Link : localOut@gnut39 queryreachespeer
Link : queryhit@server39 q_in@gnut39
Link : queryhit@server39 queryhit
Link : query_in query@gnut39
Link : connect_out@gnut39 connect
Link : disconnect_out@gnut39 disconnect
Link : qhit_out@gnut39 queryhit@session39

[session39]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 28,28,42,58,127,138,201,222,226,248,287,321,321,322,330,367,417,427,443,492,503,523,613,617,621,629,642,667,673,748,753,761,764,777,834,892,894,903,907,946
whoAmI : 39
TimeToLive : 4

[connector39]
friendlist : 36,44
whoAmI : 39 

[server39]
capacity : 60


[Peer40]
components : session40@RandomSurfer connector40@ConnectionManager gnut40@Router server40@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session40 in_online@connector40
Link : online@session40 online
Link : offline@session40 in_offline@connector40
Link : out_offline@connector40 offline
Link : query@session40 query_out
Link : query@session40 publish@server40
Link : publish@session40 publish@server40
Link : p_out@server40 publish
Link : link@server40 LinkFind
Link : remove@session40 remove@server40
Link : out_connect@connector40 connect_out
Link : out_disconnect@connector40 disconnect_out
Link : connect_in in_connect@connector40
Link : connect_in connections@gnut40
Link : q_in q_in@gnut40
Link : q_out@gnut40 q_out
Link : localOut@gnut40 peer_in@server40
Link : Link_in peer_in@server40
Link : localOut@gnut40 queryreachespeer
Link : queryhit@server40 q_in@gnut40
Link : queryhit@server40 queryhit
Link : query_in query@gnut40
Link : connect_out@gnut40 connect
Link : disconnect_out@gnut40 disconnect
Link : qhit_out@gnut40 queryhit@session40

[session40]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 5,9,13,22,27,48,83,88,113,174,181,197,203,212,228,229,252,254,288,419,428,447,455,462,474,484,485,518,574,645,692,733,743,754,796,798,863,923,931,942
whoAmI : 40
TimeToLive : 4

[connector40]
friendlist : 32,42
whoAmI : 40 

[server40]
capacity : 60


[Peer41]
components : session41@RandomSurfer connector41@ConnectionManager gnut41@Router server41@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session41 in_online@connector41
Link : online@session41 online
Link : offline@session41 in_offline@connector41
Link : out_offline@connector41 offline
Link : query@session41 query_out
Link : query@session41 publish@server41
Link : publish@session41 publish@server41
Link : p_out@server41 publish
Link : link@server41 LinkFind
Link : remove@session41 remove@server41
Link : out_connect@connector41 connect_out
Link : out_disconnect@connector41 disconnect_out
Link : connect_in in_connect@connector41
Link : connect_in connections@gnut41
Link : q_in q_in@gnut41
Link : q_out@gnut41 q_out
Link : localOut@gnut41 peer_in@server41
Link : Link_in peer_in@server41
Link : localOut@gnut41 queryreachespeer
Link : queryhit@server41 q_in@gnut41
Link : queryhit@server41 queryhit
Link : query_in query@gnut41
Link : connect_out@gnut41 connect
Link : disconnect_out@gnut41 disconnect
Link : qhit_out@gnut41 queryhit@session41

[session41]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 1,70,74,105,119,151,204,231,283,304,326,349,366,377,380,389,394,401,419,422,444,451,453,479,509,595,633,674,683,797,819,834,839,850,871,923,942,943,951,960
whoAmI : 41
TimeToLive : 4

[connector41]
friendlist : 25,30,12
whoAmI : 41 

[server41]
capacity : 60


[Peer42]
components : session42@RandomSurfer connector42@ConnectionManager gnut42@Router server42@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session42 in_online@connector42
Link : online@session42 online
Link : offline@session42 in_offline@connector42
Link : out_offline@connector42 offline
Link : query@session42 query_out
Link : query@session42 publish@server42
Link : publish@session42 publish@server42
Link : p_out@server42 publish
Link : link@server42 LinkFind
Link : remove@session42 remove@server42
Link : out_connect@connector42 connect_out
Link : out_disconnect@connector42 disconnect_out
Link : connect_in in_connect@connector42
Link : connect_in connections@gnut42
Link : q_in q_in@gnut42
Link : q_out@gnut42 q_out
Link : localOut@gnut42 peer_in@server42
Link : Link_in peer_in@server42
Link : localOut@gnut42 queryreachespeer
Link : queryhit@server42 q_in@gnut42
Link : queryhit@server42 queryhit
Link : query_in query@gnut42
Link : connect_out@gnut42 connect
Link : disconnect_out@gnut42 disconnect
Link : qhit_out@gnut42 queryhit@session42

[session42]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 2,65,91,101,115,116,130,216,218,282,289,336,366,380,410,428,458,491,496,500,547,589,599,622,625,626,631,639,662,669,731,813,849,851,860,913,921,935
whoAmI : 42
TimeToLive : 4

[connector42]
friendlist : 40,47
whoAmI : 42 

[server42]
capacity : 60


[Peer43]
components : session43@RandomSurfer connector43@ConnectionManager gnut43@Router server43@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session43 in_online@connector43
Link : online@session43 online
Link : offline@session43 in_offline@connector43
Link : out_offline@connector43 offline
Link : query@session43 query_out
Link : query@session43 publish@server43
Link : publish@session43 publish@server43
Link : p_out@server43 publish
Link : link@server43 LinkFind
Link : remove@session43 remove@server43
Link : out_connect@connector43 connect_out
Link : out_disconnect@connector43 disconnect_out
Link : connect_in in_connect@connector43
Link : connect_in connections@gnut43
Link : q_in q_in@gnut43
Link : q_out@gnut43 q_out
Link : localOut@gnut43 peer_in@server43
Link : Link_in peer_in@server43
Link : localOut@gnut43 queryreachespeer
Link : queryhit@server43 q_in@gnut43
Link : queryhit@server43 queryhit
Link : query_in query@gnut43
Link : connect_out@gnut43 connect
Link : disconnect_out@gnut43 disconnect
Link : qhit_out@gnut43 queryhit@session43

[session43]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 20,24,29,76,117,121,133,142,157,187,213,223,226,227,275,320,323,375,377,386,401,430,456,478,523,541,613,664,686,724,735,742,854,909,921,940,949
whoAmI : 43
TimeToLive : 4

[connector43]
friendlist : 16,13
whoAmI : 43 

[server43]
capacity : 60


[Peer44]
components : session44@RandomSurfer connector44@ConnectionManager gnut44@Router server44@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session44 in_online@connector44
Link : online@session44 online
Link : offline@session44 in_offline@connector44
Link : out_offline@connector44 offline
Link : query@session44 query_out
Link : query@session44 publish@server44
Link : publish@session44 publish@server44
Link : p_out@server44 publish
Link : link@server44 LinkFind
Link : remove@session44 remove@server44
Link : out_connect@connector44 connect_out
Link : out_disconnect@connector44 disconnect_out
Link : connect_in in_connect@connector44
Link : connect_in connections@gnut44
Link : q_in q_in@gnut44
Link : q_out@gnut44 q_out
Link : localOut@gnut44 peer_in@server44
Link : Link_in peer_in@server44
Link : localOut@gnut44 queryreachespeer
Link : queryhit@server44 q_in@gnut44
Link : queryhit@server44 queryhit
Link : query_in query@gnut44
Link : connect_out@gnut44 connect
Link : disconnect_out@gnut44 disconnect
Link : qhit_out@gnut44 queryhit@session44

[session44]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 46,57,60,138,140,171,245,245,278,333,352,421,424,426,431,480,531,629,718,729,744,747,809,845,867,869,884,887,924
whoAmI : 44
TimeToLive : 4

[connector44]
friendlist : 39,36,45
whoAmI : 44 

[server44]
capacity : 60


[Peer45]
components : session45@RandomSurfer connector45@ConnectionManager gnut45@Router server45@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session45 in_online@connector45
Link : online@session45 online
Link : offline@session45 in_offline@connector45
Link : out_offline@connector45 offline
Link : query@session45 query_out
Link : query@session45 publish@server45
Link : publish@session45 publish@server45
Link : p_out@server45 publish
Link : link@server45 LinkFind
Link : remove@session45 remove@server45
Link : out_connect@connector45 connect_out
Link : out_disconnect@connector45 disconnect_out
Link : connect_in in_connect@connector45
Link : connect_in connections@gnut45
Link : q_in q_in@gnut45
Link : q_out@gnut45 q_out
Link : localOut@gnut45 peer_in@server45
Link : Link_in peer_in@server45
Link : localOut@gnut45 queryreachespeer
Link : queryhit@server45 q_in@gnut45
Link : queryhit@server45 queryhit
Link : query_in query@gnut45
Link : connect_out@gnut45 connect
Link : disconnect_out@gnut45 disconnect
Link : qhit_out@gnut45 queryhit@session45

[session45]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 20,39,59,92,142,175,244,261,262,289,305,321,356,358,370,396,432,501,516,544,546,627,750,760,813,821,829,842,844,873,907,926,960
whoAmI : 45
TimeToLive : 4

[connector45]
friendlist : 36,21,44
whoAmI : 45 

[server45]
capacity : 60


[Peer46]
components : session46@RandomSurfer connector46@ConnectionManager gnut46@Router server46@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session46 in_online@connector46
Link : online@session46 online
Link : offline@session46 in_offline@connector46
Link : out_offline@connector46 offline
Link : query@session46 query_out
Link : query@session46 publish@server46
Link : publish@session46 publish@server46
Link : p_out@server46 publish
Link : link@server46 LinkFind
Link : remove@session46 remove@server46
Link : out_connect@connector46 connect_out
Link : out_disconnect@connector46 disconnect_out
Link : connect_in in_connect@connector46
Link : connect_in connections@gnut46
Link : q_in q_in@gnut46
Link : q_out@gnut46 q_out
Link : localOut@gnut46 peer_in@server46
Link : Link_in peer_in@server46
Link : localOut@gnut46 queryreachespeer
Link : queryhit@server46 q_in@gnut46
Link : queryhit@server46 queryhit
Link : query_in query@gnut46
Link : connect_out@gnut46 connect
Link : disconnect_out@gnut46 disconnect
Link : qhit_out@gnut46 queryhit@session46

[session46]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 8,45,59,83,109,172,178,181,191,194,239,253,256,347,350,364,432,460,468,479,479,575,614,641,670,756,759,771,810,842,848,864,890,905,910,915,949
whoAmI : 46
TimeToLive : 4

[connector46]
friendlist : 23
whoAmI : 46 

[server46]
capacity : 60


[Peer47]
components : session47@RandomSurfer connector47@ConnectionManager gnut47@Router server47@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session47 in_online@connector47
Link : online@session47 online
Link : offline@session47 in_offline@connector47
Link : out_offline@connector47 offline
Link : query@session47 query_out
Link : query@session47 publish@server47
Link : publish@session47 publish@server47
Link : p_out@server47 publish
Link : link@server47 LinkFind
Link : remove@session47 remove@server47
Link : out_connect@connector47 connect_out
Link : out_disconnect@connector47 disconnect_out
Link : connect_in in_connect@connector47
Link : connect_in connections@gnut47
Link : q_in q_in@gnut47
Link : q_out@gnut47 q_out
Link : localOut@gnut47 peer_in@server47
Link : Link_in peer_in@server47
Link : localOut@gnut47 queryreachespeer
Link : queryhit@server47 q_in@gnut47
Link : queryhit@server47 queryhit
Link : query_in query@gnut47
Link : connect_out@gnut47 connect
Link : disconnect_out@gnut47 disconnect
Link : qhit_out@gnut47 queryhit@session47

[session47]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 7,81,85,109,147,159,161,271,275,341,346,355,360,384,385,428,452,455,457,458,469,480,510,532,547,563,600,645,660,679,717,781,818,838,871,884,892,963
whoAmI : 47
TimeToLive : 4

[connector47]
friendlist : 42
whoAmI : 47 

[server47]
capacity : 60


[Peer48]
components : session48@RandomSurfer connector48@ConnectionManager gnut48@Router server48@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session48 in_online@connector48
Link : online@session48 online
Link : offline@session48 in_offline@connector48
Link : out_offline@connector48 offline
Link : query@session48 query_out
Link : query@session48 publish@server48
Link : publish@session48 publish@server48
Link : p_out@server48 publish
Link : link@server48 LinkFind
Link : remove@session48 remove@server48
Link : out_connect@connector48 connect_out
Link : out_disconnect@connector48 disconnect_out
Link : connect_in in_connect@connector48
Link : connect_in connections@gnut48
Link : q_in q_in@gnut48
Link : q_out@gnut48 q_out
Link : localOut@gnut48 peer_in@server48
Link : Link_in peer_in@server48
Link : localOut@gnut48 queryreachespeer
Link : queryhit@server48 q_in@gnut48
Link : queryhit@server48 queryhit
Link : query_in query@gnut48
Link : connect_out@gnut48 connect
Link : disconnect_out@gnut48 disconnect
Link : qhit_out@gnut48 queryhit@session48

[session48]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 91,119,123,125,127,133,185,263,316,320,329,337,426,445,452,519,520,525,548,549,553,628,648,692,701,709,711,769,784,801,805,812,819,820,835,890,916,922,934
whoAmI : 48
TimeToLive : 4

[connector48]
friendlist : 37,17
whoAmI : 48 

[server48]
capacity : 60


[Peer49]
components : session49@RandomSurfer connector49@ConnectionManager gnut49@Router server49@Repository
out : query_out
out : q_out
out : connect_out
out : disconnect_out
out : online
out : offline
out : disconnect
out : connect
out : queryhit
out : publish
out : queryreachespeer
out : LinkFind
in : query_in 
in : q_in
in : connect_in
in : Link_in
Link : online@session49 in_online@connector49
Link : online@session49 online
Link : offline@session49 in_offline@connector49
Link : out_offline@connector49 offline
Link : query@session49 query_out
Link : query@session49 publish@server49
Link : publish@session49 publish@server49
Link : p_out@server49 publish
Link : link@server49 LinkFind
Link : remove@session49 remove@server49
Link : out_connect@connector49 connect_out
Link : out_disconnect@connector49 disconnect_out
Link : connect_in in_connect@connector49
Link : connect_in connections@gnut49
Link : q_in q_in@gnut49
Link : q_out@gnut49 q_out
Link : localOut@gnut49 peer_in@server49
Link : Link_in peer_in@server49
Link : localOut@gnut49 queryreachespeer
Link : queryhit@server49 q_in@gnut49
Link : queryhit@server49 queryhit
Link : query_in query@gnut49
Link : connect_out@gnut49 connect
Link : disconnect_out@gnut49 disconnect
Link : qhit_out@gnut49 queryhit@session49

[session49]
probabilityofactivity : 0.7
probabilityToIgnore : 0.15

betweenquerydistribution : lognormal
betweenquerymean : 2.63
betweenquerydeviation : 3.35

beforequerydistribution : lognormal 
beforequerymean : 8
beforequerydeviation : 0.3

offlinetimedistribution : exponential
offlinetimemean : 2000

NumQueries : 965
doclist : 14,47,96,116,144,152,156,165,165,198,211,225,241,267,290,317,331,360,395,402,415,481,504,529,554,591,593,662,671,704,712,749,756,769,776,811,815,883,901,902,903,913
whoAmI : 49
TimeToLive : 4

[connector49]
friendlist : 1
whoAmI : 49 

[server49]
capacity : 60


[Network]
 components : net@PhysicalNetwork LTS@NetworkGraph
out : c_out0
out : c_out1
out : c_out2
out : c_out3
out : c_out4
out : c_out5
out : c_out6
out : c_out7
out : c_out8
out : c_out9
out : c_out10
out : c_out11
out : c_out12
out : c_out13
out : c_out14
out : c_out15
out : c_out16
out : c_out17
out : c_out18
out : c_out19
out : c_out20
out : c_out21
out : c_out22
out : c_out23
out : c_out24
out : c_out25
out : c_out26
out : c_out27
out : c_out28
out : c_out29
out : c_out30
out : c_out31
out : c_out32
out : c_out33
out : c_out34
out : c_out35
out : c_out36
out : c_out37
out : c_out38
out : c_out39
out : c_out40
out : c_out41
out : c_out42
out : c_out43
out : c_out44
out : c_out45
out : c_out46
out : c_out47
out : c_out48
out : c_out49
out : route_out0
out : route_out1
out : route_out2
out : route_out3
out : route_out4
out : route_out5
out : route_out6
out : route_out7
out : route_out8
out : route_out9
out : route_out10
out : route_out11
out : route_out12
out : route_out13
out : route_out14
out : route_out15
out : route_out16
out : route_out17
out : route_out18
out : route_out19
out : route_out20
out : route_out21
out : route_out22
out : route_out23
out : route_out24
out : route_out25
out : route_out26
out : route_out27
out : route_out28
out : route_out29
out : route_out30
out : route_out31
out : route_out32
out : route_out33
out : route_out34
out : route_out35
out : route_out36
out : route_out37
out : route_out38
out : route_out39
out : route_out40
out : route_out41
out : route_out42
out : route_out43
out : route_out44
out : route_out45
out : route_out46
out : route_out47
out : route_out48
out : route_out49
in : peer_connect
in : peer_disconnect
in : inroute
in : in_online
in : in_offline
Link : peer_connect connect_in@LTS
Link : peer_disconnect disconnect_in@LTS
Link : in_online peer_online@LTS
Link : in_offline peer_offline@LTS
Link : inroute inroute@net
Link : c_out0@LTS c_out0
Link : c_out1@LTS c_out1
Link : c_out2@LTS c_out2
Link : c_out3@LTS c_out3
Link : c_out4@LTS c_out4
Link : c_out5@LTS c_out5
Link : c_out6@LTS c_out6
Link : c_out7@LTS c_out7
Link : c_out8@LTS c_out8
Link : c_out9@LTS c_out9
Link : c_out10@LTS c_out10
Link : c_out11@LTS c_out11
Link : c_out12@LTS c_out12
Link : c_out13@LTS c_out13
Link : c_out14@LTS c_out14
Link : c_out15@LTS c_out15
Link : c_out16@LTS c_out16
Link : c_out17@LTS c_out17
Link : c_out18@LTS c_out18
Link : c_out19@LTS c_out19
Link : c_out20@LTS c_out20
Link : c_out21@LTS c_out21
Link : c_out22@LTS c_out22
Link : c_out23@LTS c_out23
Link : c_out24@LTS c_out24
Link : c_out25@LTS c_out25
Link : c_out26@LTS c_out26
Link : c_out27@LTS c_out27
Link : c_out28@LTS c_out28
Link : c_out29@LTS c_out29
Link : c_out30@LTS c_out30
Link : c_out31@LTS c_out31
Link : c_out32@LTS c_out32
Link : c_out33@LTS c_out33
Link : c_out34@LTS c_out34
Link : c_out35@LTS c_out35
Link : c_out36@LTS c_out36
Link : c_out37@LTS c_out37
Link : c_out38@LTS c_out38
Link : c_out39@LTS c_out39
Link : c_out40@LTS c_out40
Link : c_out41@LTS c_out41
Link : c_out42@LTS c_out42
Link : c_out43@LTS c_out43
Link : c_out44@LTS c_out44
Link : c_out45@LTS c_out45
Link : c_out46@LTS c_out46
Link : c_out47@LTS c_out47
Link : c_out48@LTS c_out48
Link : c_out49@LTS c_out49
Link : route_out0@net route_out0
Link : route_out1@net route_out1
Link : route_out2@net route_out2
Link : route_out3@net route_out3
Link : route_out4@net route_out4
Link : route_out5@net route_out5
Link : route_out6@net route_out6
Link : route_out7@net route_out7
Link : route_out8@net route_out8
Link : route_out9@net route_out9
Link : route_out10@net route_out10
Link : route_out11@net route_out11
Link : route_out12@net route_out12
Link : route_out13@net route_out13
Link : route_out14@net route_out14
Link : route_out15@net route_out15
Link : route_out16@net route_out16
Link : route_out17@net route_out17
Link : route_out18@net route_out18
Link : route_out19@net route_out19
Link : route_out20@net route_out20
Link : route_out21@net route_out21
Link : route_out22@net route_out22
Link : route_out23@net route_out23
Link : route_out24@net route_out24
Link : route_out25@net route_out25
Link : route_out26@net route_out26
Link : route_out27@net route_out27
Link : route_out28@net route_out28
Link : route_out29@net route_out29
Link : route_out30@net route_out30
Link : route_out31@net route_out31
Link : route_out32@net route_out32
Link : route_out33@net route_out33
Link : route_out34@net route_out34
Link : route_out35@net route_out35
Link : route_out36@net route_out36
Link : route_out37@net route_out37
Link : route_out38@net route_out38
Link : route_out39@net route_out39
Link : route_out40@net route_out40
Link : route_out41@net route_out41
Link : route_out42@net route_out42
Link : route_out43@net route_out43
Link : route_out44@net route_out44
Link : route_out45@net route_out45
Link : route_out46@net route_out46
Link : route_out47@net route_out47
Link : route_out48@net route_out48
Link : route_out49@net route_out49
